### ISSUE TITLE
Remove unused variables

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#134]
Removing the `-Wno-unused` flag from VIC's makefile reveals 401 unused variables in the current VIC source code.  I propose these be removed (or used as they were originally intended).  

``` bash
CalcAerodynamic.c:22:13: warning: 'vcid' defined but not used [-Wunused-variable]
CalcBlowingSnow.c:147:7: warning: unused variable 'count' [-Wunused-variable]
CalcBlowingSnow.c:142:16: warning: unused variable 'temp3' [-Wunused-variable]
CalcBlowingSnow.c:142:10: warning: unused variable 'temp' [-Wunused-variable]
...
```

**Comment by bartnijssen** [comment]
There are still some unused variables in develop:vic_run/src/CalcBlowingSnow.c
```
:511:24: warning: unused parameter 'AirDens' [-Wunused-parameter]
:512:24: warning: unused parameter 'ZO' [-Wunused-parameter]
:518:24: warning: unused parameter 'Zrh' [-Wunused-parameter]
:710:21: warning: unused parameter 'Tsnow' [-Wunused-parameter]
:711:21: warning: unused parameter 'Tair' [-Wunused-parameter]
:810:30: warning: unused parameter 'es' [-Wunused-parameter]
:812:30: warning: unused parameter 'AirDens' [-Wunused-parameter]
:814:30: warning: unused parameter 'EactAir' [-Wunused-parameter]
:815:30: warning: unused parameter 'F' [-Wunused-parameter]
:819:30: warning: unused parameter 'Zrh' [-Wunused-parameter]
```
I can delete them, but just want to make sure first that they were not kept for a reason.

**Comment by jhamman** [comment]
I seem to remember there being a reason that I left some of those around.  I think it had to do with the solvers used in `CalcBlowingSnow.c`.  Just be careful to track any function pointers or variable argument lists carefully.  If it can be done cleanly, by all means, let's get rid of them.

**Comment by bartnijssen** [comment]
OK - I seem to remember the same - so I will leave it alone for now. When I have time I may go through and document within CalcBlowingSnow why these vars cannot be deleted.
