### ISSUE TITLE
Make VIC code citable?

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#176]
How do we want the VIC model to be cited?

Is citing the [*Primary Historical Reference*: Liang et al. (1994)](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/References.shtml#VIC) sufficient?  Obviously, there have been many changes to the VIC model since 1994.

I've recently run across Github's page on [Making your code citable](https://guides.github.com/activities/citable-code/) and thought I would bring it up here to see if anyone had thoughts.  In short, we have the option of tying a particular [DOI](http://en.wikipedia.org/wiki/Digital_object_identifier) to the model source code itself, allowing individual releases to be directly citable.  Below is a list of links that outline how this can be done:
- [Github: Making your code citable](https://guides.github.com/activities/citable-code/)
- [Mozilla Science Lab](http://mozillascience.org)
  - [Introduction](http://mozillascience.org/code-as-a-research-object-a-new-project/)
  - [Code as a Research Object](http://mozillascience.github.io/code-research-object/)
- [Zendo](https://zenodo.org/):  "Zenodo is an open dependable home for the long-tail of science, enabling researchers to share and preserve any research outputs in any size, any format and from any science."
- [Figshare](http://figshare.com/):  "figshare is a repository where users can make all of their research outputs available in a citable, shareable and discoverable manner."

**Comment by bartnijssen** [comment]
I registered with Zenodo (the entity issuing the doi) and linked the VIC repo. A DOI will be generated automatically when a new VIC release is created. I have not found a way through Zenodo to create a DOI for an existing release.

**Comment by jhamman** [comment]
This is great.  I did a bit of reading on this and we will need to upload previously released versions we want DOIs for manually on Zenodo.  Sounds like a fun task.

**Comment by bartnijssen** [comment]
OK - I'll check into that. I can at least upload the most recent releases and then the main release for the previous versions: 4.0.6 - 4.1.1

**Comment by jhamman** [comment]
I recently asked Zenodo if there was any way to automate the upload process for previous releases and this was their answer: 
> Thanks for your message. Unfortunately you'll have to manually upload them for now. We are planning to improve our GitHub integration in the late autumn and one of them is exactly this use case.
