### ISSUE TITLE
Forcing file dates

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#18]
**Description** - Require forcing files to contain dates/times, and remove this information from the global parameter file.
**Optional?**	- No
**Comment** - This would be included by using properly formatted netCDF forcings.

See issues #17 and #23 for more details.

**Comment by jhamman** [comment]
@bartnijssen and @tbohn -

What do we think about this issue given where we stand with 5.0 right now. My original thought was to require a header and date/time columns and have VIC use them when determining the forcing fields. This would require a bit of work so I'd like to discuss how to proceed.

**Comment by tbohn** [comment]
It's not a big deal for classic, as I mentioned above - classic already has the ability to read a file that has a header and date fields.  Although all classic does at the moment is ignore the data.  So to make it a requirement, you'd have to have VIC at least read some parts of the header and date fields and complain if these weren't present or weren't valid.

I don't know how much work this would entail for image/cesm - I guess you'd read the variable names from the global param file forcing section?  You know better than I do.

**Comment by jhamman** [comment]
> I don't know how much work this would entail for image/cesm

This change would only impact the Classic Driver.

**Comment by tbohn** [comment]
Oh, right, somehow I was thinking of user-specified variable names as part of the deal - but of course you can require that the ascii file headers have only the exact variable names that VIC expects.

**Comment by bartnijssen** [comment]
Still would be my preference to include it since the changes in 5.0 are not required to be backwards compatible anyway. If we do not do this (actually read and check the dates), then we should at least explain in the documentation how people can already include a date (per Ted's comments above).

**Comment by bartnijssen** [comment]
We should just indicate in the documentation how this can be handled and recommend that people include a date. This is not an issue for image mode anyway.

Changing the label to documentation.

**Comment by bartnijssen** [comment]
Continued in #579
