### ISSUE TITLE
standardize printf format specifiers

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#193]
The C standard are a bit ambiguous about how to specify integer and floating point types in `printf()` strings.  All floating point variables are promoted to `double` and all integer variables (regardless of sign or length) are promoted to int.  Therefore, `printf` accepts the promoted format of `%f` and `%d` or the original type format (e.g. `%lf`, `%hu`, etc.).

@bartnijssen has proposed (in #188) standardizing these to the simpler promoted format (`%f` and `%d`) for all `printf()` statements in the code.  This includes all logging statements.  

It is important to realize that this does not apply to `scanf()` type reader functions where the precise datatype format does matter and errors will likely raise compiler errors.

**Comment by bartnijssen** [comment]
Closed per #200
