### ISSUE TITLE
retag 4.2.1 to 4.2.a

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#203]
Hot fix naming for 4.2 will be 

4.2.a
4.2.b
etc. As for release 4.1.2, the letter designates it as a hotfix.

From 5.X on, the releases will be

`<major release>.<minor release>.<bug fix>`

as per issue #49

**Comment by jhamman** [comment]
closed.  see tags [`4.2`](https://github.com/UW-Hydro/VIC/releases/tag/VIC.4.2) and [`4.2.a`](https://github.com/UW-Hydro/VIC/releases/tag/VIC.4.2.a).  `4.2.b` will be released tomorrow.
