### ISSUE TITLE
Add simulation identifier to output files.  

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#205]
We've all found ourselves wondering what the difference is between `data_48.1875_-120.6875` and `data_48.1875_-120.6875`.  I propose adding a simulation identifier to the global parameter file so that these files would look more like `sim1_data_48.1875_-120.6875` and `sim2_data_48.1875_-120.6875`.  

This may seem like a small detail but the classic driver has few other mechanisms to add meaningful metadata to model output.  

This would transfer to the image mode drivers as well: `sim1_data_vic_${date/time}.nc`.

**Comment by tbohn** [comment]
You can specify the prefix of the output files in the global parameter
file.  That's what the functionality is there for...

**Comment by jhamman** [comment]
If only it were used that way...

**Comment by bartnijssen** [comment]
Isn't it? I think I have used this in the past. I'd rather leave it up to the user and may be just point out that this functionality exists. I can imagine cases where having the same name is actually an advantage (overwrite files) and the flexibility already exists to do this. 

To me this is a workflow issue on the part of the user, not something we need to mandate on the programming side. Maybe we just need to highlight this (we could create a brief "VIC Best Practices" document that specifies this.

**Comment by jhamman** [comment]
closing in lieu of #226.
