### ISSUE TITLE
Set logging level

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#218]
The current logging system only allows for the silencing of the `debug` log level by setting the `NDEBUG` variable. A useful extension of this would be to replace `NDEBUG` with `LOG_LVL` and to extend the logic in `vic_log.h` to allow for silencing the `log_info` and `log_warn` log levels as well.

**Comment by jhamman** [comment]
@bartnijssen - are we okay with this being a compile time option? I'm not sure if it is possible to override the compile time macros at runtime.

**Comment by bartnijssen** [comment]
I'd be OK with that
