### ISSUE TITLE
Coupled Streamflow Routing

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#24]
**Description** - Couple [RVIC](https://github.com/jhamman/RVIC) to image mode drivers
**Optional?**   - Yes

See issue #7 for more details regarding the image mode drivers.

**Comment by wietsefranssen** [comment]
Joe, can you provide me an example setup of a real basin (also with a routing param file)? Or give me some scripts (and howto) to make it myself? Then we can test the routing module and compare it with measured data to get an idea of the order of magnitude of the discharge.

**Comment by jhamman** [comment]
I'm not entirely sure what you are asking for.  Are you looking for an additional VIC or RVIC setup?  I can certainly help you put those together but I don't have anything prepared off hand.

**Comment by bartnijssen** [comment]
See issue #231 and related
