### ISSUE TITLE
Overhaul the subdaily disaggregation logic in initialize_atmos.c

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#240]
When we changed the default timestep units to seconds (#188), we introduced a number of bugs into the subdail disaggregation of forcing variables in `initialize_atmos.c`. Looking at the code, there is a lot of repeated logic that could be abstracted to individual functions.  This will greatly reduce the likelihood of bugs coming from slightly different implementations with the same goal. 

I'll take point on this issue and will split the work into three steps:
- [ ] Create functions for the various forms of subdaily disaggregation supported in `initialize_atmos`.
- [ ] Replace repeated sections of code with these functions
- [ ] Test, test, test.

xref #42 and #188 

cc @tbohn: I may need a bit of guidance as I go through this.

**Comment by bartnijssen** [comment]
Can you point to some examples? The MTCLIM was wrapped with as few changes to that code as possible and I would like to keep it that way. Any VIC code we can of course change.

**Comment by tbohn** [comment]
I think Joe is referring to the logic in initialize_atmos.c for
transferring data from the MTCLIM data structures and the forcing data
structures into the atmos data structure.

Ted

**Comment by tbohn** [comment]
OK, as per @jhamman 's suggestion, I'll take a look at getting this subroutinized.

**Comment by jhamman** [comment]
Alright, I think I've fixed some of these issues shown below but will have to rerun this test when I get back to Seattle.  A summary of what where I see the subdaily disaggregation (check these boxes when we are satisfied that things are working):

- [ ] Precipitation: looks right, need to plot subdaily subset
- [ ] Air Temp: looks right, need to plot subdaily subset
- [ ] Shortwave: Units problem, needs work
- [ ] Longwave: Units and indexing problem, needs work
- [ ] Density: broken
- [ ] Pressure: broken
- [ ] VP: broken
- [ ] Wind: looks right, need to plot subdaily subset

![stehekin_forcings](https://cloud.githubusercontent.com/assets/2443309/9913024/72a457a8-5c5f-11e5-83e9-48a4f06c5c73.png)
*Figure: Comparison of input forcings for one grid cell (48.1875, -120.6875) in the Stehekin test dataset with the disaggregated hourly forcings for VIC 4.2.b and the develop branch.*

Figure current as of January 26, 2015.

**Comment by tbohn** [comment]
Thanks @jhamman.  Are you actively working on this?  What kind of timeframe did you have in mind for this?  I can get to this tomorrow, maybe even later today, but I do have some other things to work on that need to be my top priority today.

**Comment by jhamman** [comment]
Actually, I also have this plot for a shorter period:

![stehekin_forcings2](https://cloud.githubusercontent.com/assets/2443309/9913506/fcc0d072-5c61-11e5-97e0-bdd275423426.png)
*Figure: Same data as above but for shorter time period and only showing VIC 4.2.b (left) and develop branch (right).*

**Comment by jhamman** [comment]
@tbohn  - 

After talking with @bartnijssen, we have come up with another path forward here. The basic idea is to remove the `MTCLIM` and subdaily disaggregation entirely from the Classic Driver.  

1. Remove `MTCLIM`
2. Replace `initialize_atmos` with `vic_force`, basically a function to pack the `atmos_struct`
3. Create a standalone forcing generator tool based on `initialize_atmos` that uses the VIC.4.2 C code to do the MTCLIM/disaggregation  

This greatly simplifies the Classic Driver implementation but requires us to develop the stand alone tool in the near future.

@tbohn - how do you see this working out?

**Comment by tbohn** [comment]
That makes more sense to me.  Will the stand-alone tool be based on your python tool?  Or will it be in c?

Seems to me that the stand-alone tool will need netcdf i/o (in addition to classic ascii), so maybe python is the way to go?

**Comment by bartnijssen** [comment]
I think we should do the standalone tool in two steps:

1. The existing VIC code with all (most) VIC functionality stripped out. This tool would be able to reproduce exactly the hourly VIC forcings that we had in VIC 4.2. That way we are not making too many changes at once.

2. Switch to a python-based forcing tool, which may or may not have additional functionality.

Creating (1) would hopefully be straightforward. It would be what VIC produces with the `OUTPUT_FORCE` option. It'll require a few updates to handle the subhourly timestep.

**Comment by jhamman** [comment]
closed as wont fix since we removed sub-daily dis-aggregation all together in #288.
