### ISSUE TITLE
Bug in unused function.

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#243]
I'm writing unit tests using the python driver and I've found this puzzler. First, my test was failing because the function always returns a value of 1.0. Second, in looking into this a bit deeper, I don't think this function is ever used in `vic_run` or any of the drivers.

So the question is, should we be using the function somewhere or should I remove it?

```C
double
modify_Ksat(double Temp)
{
    extern option_struct options;

    double               Factor;

    /** formula generated by multiple regression against kinematic
        viscosity data from the Handbook of Chemistry and Physics **/
    if (options.FROZEN_SOIL) {
        Factor = 0.003557 / (0.006534 - 0.0002282 * Temp + 4.794e-6 * (Temp) *
                             (Temp) - 4.143e-8 * (Temp) * (Temp) * (Temp));
    }
    else {
        Factor = 1.;
    }

    if (Factor > 2.) {
        Factor = 2.;
    }

    return (1.0);
}
```

ref: https://github.com/UW-Hydro/VIC/blob/develop/vic/vic_run/src/modify_Ksat.c

**Comment by jhamman** [comment]
Also, `exp_interp` in the same source file is not used anywhere in VIC right now.

**Comment by bartnijssen** [comment]
Fine with me. @tbohn : Can you comment?

**Comment by bartnijssen** [comment]
BTW - note that `linear_interp()` in that file is used in a number of places, so we would need to retain that one.
