### ISSUE TITLE
Move veg_hist logic outside of vic_run()

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#275]
Time-varying veg parameters such as LAI, vegcover, and albedo should all be passed to vic_run() via a single data structure, containing only the elements of these arrays that apply to the current time step.  The logic to choose the source of these parameter values (from veg_lib, veg_parameter file, or veg_hist file) should happen outside of vic_run().  vic_run() should not need to know anything about the current record (or month).

**Comment by tbohn** [comment]
Since reading vegcover from the parameter file in image mode isn't implemented, probably should include implementing it in this issue.

**Comment by tbohn** [comment]
Regarding my previous comment: I think reading vegcover from the parameter file in image mode should be a separate issue, since it's not related to veg_hist.  I will open a separate issue for that, and create a separate pull request.

On the other hand, I think reading veg_hist from netcdf files (issue #325) *should* be included in this set of code changes since moving veg_hist logic out of vic_run will move it into the driver code, which is where reading veg_hist from netcdf files would have to happen.

**Comment by tbohn** [comment]
Question about the preferred method of solving this issue:

The offending block of code in vic_run() is an assignment of veg_hist variables for the given time step to the veg_var structure.  I could naively move that block up into the parent function (vic_<mode>, where <mode> = "classic" or "image"), but that seems a bit ugly/too detailed for the top-level function.  Alternatively I could create a small function (e.g., "update_veg_var()") that would do the assignment, and then have vic_<mode> call that function.  Any opinions?

**Comment by tbohn** [comment]
For image mode, I propose the following:
1. change dimensions of veg_hist to only store one time step's worth of values
2. remove the block that assigns the monthly veg_con climatology to veg_hist
3. implement reading of veg_hist from netcdf files (but only if the options.*_SRC are set to FROM_VEGHIST)
4. create a function that assigns either the veg_con or the veg_hist values appropriate to the current time step (over the whole domain) to veg_var, as determined by the options.*_SRC settings; this function will be called from vic_image() before calling vic_image_run(); veg_hist will not be passed to vic_image_run()

**Comment by tbohn** [comment]
The plan as it currently stands is to have a new function "update_step_vars()" do the assignment of veg_hist to veg_var, and I think this single function will work with both classic and image drivers.

**Comment by tbohn** [comment]
While fixing this issue will help address the presence of references to current date or record in vic_run(), it won't fix all of them.  I've opened a separate issue (issue #358) to explicitly address removing references to date or record from vic_run().

**Comment by jhamman** [comment]
closed via #359
