### ISSUE TITLE
remove log_ncerr logging macro

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#277]
It turns out, we don't need the `log_ncerr` macro, the `log_ncerr` does the same thing: 

`log_ncerr(status);` just prints the error string associated with status, e.g.

`[ERROR] /p/home/jhamman/rasm_vic5/models/lnd/vic/vic/drivers/cesm/src/get_nc_field.c:49: errno: No such file or directory`

it would be better to use 

`log_err("%s", "a useful message");` to print out a bit more information.  `log_err` retrieves the error number and prints the error string as well. Which would print something like this:

`[ERROR] /p/home/jhamman/rasm_vic5/models/lnd/vic/vic/drivers/cesm/src/get_nc_field.c:49: errno: No such file or directory: trouble opening ${VIC5TESTDIR}/vic_params_wr50a_vic5.0.dev.nc`

**Comment by bartnijssen** [comment]
Closed per #279
