### ISSUE TITLE
global_param.measure_h is never used

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#283]
A grep survey of the `vic_run` and the image and classic drivers shows that the `measure_h` member of the `global_param_struct` is never used.

The VIC [docs](http://vic.readthedocs.org/en/latest/Documentation/GlobalParam/) indicate that `measure_h` is supposed to represent the "Height of humidity measurement".  

Since it is not being used, should it be removed?

**Comment by bartnijssen** [comment]
This was to allow for differences in height between the wind measurement and the temperature / humidity measurements. Not sure where / when this distinction was removed (or maybe it was never implemented?). I think we may want to keep this distinction, but if it truly is never used there may be no need for these.

@tbohn: Please comment

**Comment by tbohn** [comment]
Unfortunately I don't recall at this point.

**Comment by bartnijssen** [comment]
@jhamman : is there an easy way to search the revision history for `measure_h`?

**Comment by jhamman** [comment]
It seems to me this was added in [this](https://github.com/UW-Hydro/VIC/blame/9a6d8f323823d9df0b16717029779a81be9b67c1/src/vicNl_def.h#L901) back in 2000.  Even in that commit, the value was not used.

**Comment by bartnijssen** [comment]
OK - in that case I am fine with removing it. I'll accept the PR
