### ISSUE TITLE
Move VIC ATBD away from top of references section

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#286]
The VIC algorithm theoretical basis document (ATBD) has never been published.  Yet it has been cited over 30 times in the literature as a "reference" for the VIC model.  Its position at the top of the references page, above Liang et al (1994), may be the reason for this.  When I inserted a reference to the VIC ATBD, we were under the impression that the ATBD was soon to be published, and we thought that the VIC ATBD would be a logical next step for people who needed more detailed information about VIC than the model overview provides.

I propose moving the reference for the ATBD into the general references list and placing emphasis on Liang et al 1994.  Perhaps (somewhere, not necessarily on the references page) there should be an example of how the VIC model should preferably be cited, if @bartnijssen has a preference.

**Comment by jhamman** [comment]
I'd support your plan @tbohn . Issue any PRs against the develop branch.

**Comment by bartnijssen** [comment]
Agreed - we should just make the VIC ATBD downloadable from docs and refer to it from the VIC documentation, but remove it from the formal references (or move it down). It should definitely not be listed as the primary reference. We should also make it explicit in the README that Liang et al. 1994 is the primary reference.
