### ISSUE TITLE
Possibly unused carbon parameters

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#293]
Determine which carbon parameters (Catm, fdir, coszen, par) need to be supplied as inputs.  Remove those that are unnecessary.

**Comment by tbohn** [comment]
All of these variables are used:
Catm is used in canopy_assimilation() to compute photosynthesis.
Fdir is used in faparl() to compute the fraction of absorbed PAR, which is used in canopy_assimilation().
PAR is used in canopy_assimilation().
coszen is used in both faparl() and compute_Nscale_factors().

I propose moving the estimation of some of these carbon-specific input variables to the python forcing disaggregator.

Currently, these variables are estimated as follows:
Catm: vic_force() estimates this from a constant in a .h file.
PAR: vic_force() estimates this as a constant fraction of shortwave.
FDIR: This is computed in MTCLIM and passed to initialize_atmos() - presumably now this happens in the python tool.
coszen: computed in compute_coszen(), which was in turn called by initialize_atmos() but is not currently called by vic_force().  It is **also** called by compute_Nscale_factors(), in order to get the value of coszen at noon.

I can imagine Catm and FDIR being supplied by models or observations, and they are not generally constant, so it would make sense to keep them in the atmos data structure and have the python tool handle populating them (from user-supplied inputs or defaults - a constant in the case of Catm and the synthetic version from MTCLIM in the case of FDIR).

However, coszen is completely determined by solar geometry, so in some sense, it's redundant to store it in the atmos data structure.  If we are concerned about memory, then we could remove coszen from atmos data and just compute it as needed, which is currently only in the carbon code.

PAR seems to be a similar situation.  I need to do some research to find out if it typically changes much over time.  I suppose it could become a different fraction of total shortwave under various atmospheric conditions.  If so, we'd need it in the atmos structure.

**Comment by tbohn** [comment]
I propose that we remove coszen from the atmos structure and only compute as needed within the carbon code.

For the other 3 variables, I propose keeping them in the atmos structure for now.  However, if we would like to reduce memory usage, and decide to only allocate them if carbon is TRUE, I think that to accomplish that we would need to split the carbon variables out into a separate structure analogous to atmos.  This could be combined with replacing the array of forcing files with a set of different files dedicated to different inputs such as veg_hist and channel_in.

**Comment by jhamman** [comment]
@tbohn - 

I'm fine with this plan.  It seems easy enough not to allocate memory for carbon only variables.

**Comment by tbohn** [comment]
OK, so does that mean I *should* make allocation of the pointers for carbon variables conditional?  I can do that for channel_in as well.

I will make this happen identically in all drivers.

**Comment by jhamman** [comment]
Yes, why don't you just add that to your `remove_mtclim` branch.

**Comment by tbohn** [comment]
OK, will do.

**Comment by tbohn** [comment]
One more issue to resolve: whether to leave assignment of default values of these variables in vic_force() or to move them into the python tool.

For classic mode, I see no problem with moving these estimates to the python tool, and requiring that they be supplied as inputs to VIC.  But for image mode, should we require these variables to be supplied as inputs (if carbon is turned on)?

If VIC is coupled to an atmospheric model that doesn't compute carbon-related variables like Catm or PAR, I suppose we could put logic in vic_force() to estimate them - this could apply to the classic driver too.  For Fdir, classic mode could rely on the python tool to pull it from MTCLIM.  But for image mode, in a coupled situation, we'd need to require Fdir from the atmospheric model (or Fclear at least; vic_force() could then compute Fdir as a simple function of Fclear).

What do you think?  If carbon is TRUE, should either Fdir or Fclear (or tskc) be required as an input?  I'd have to add tskc back in...

**Comment by jhamman** [comment]
Yes, since they are forcing variables, I think we should remove default assignments. I think we want to get out of the business of creating forcing variables in VIC.

**Comment by tbohn** [comment]
OK, will do.  So, I'll just make Catm, PAR, and Fdir all required input variables when carbon is true, in all drivers.

**Comment by tbohn** [comment]
I think this issue was resolved a while back, but I'm having trouble locating the PR...

**Comment by tbohn** [comment]
OK, this issue was resolved by PR #288.  @jhamman I think we can close this issue.

**Comment by jhamman** [comment]
okay, thanks @tbohn 

closed via #288
