### ISSUE TITLE
BUG: Output timestamp is 24 hours off at midnight

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#298]
I'm in the process of working through a list of comparisons between VIC 4.2 and the current VIC 5 develop branch. There will probably be more bug reports like this one.

Below, I'm showing the tabular output from a simulation where the midnight timestamp is for the previous day. 

<table>  <thead>    <tr style="text-align: right;">      <th></th>      <th>AIR_TEMP</th>    </tr>  </thead>  <tbody>    <tr>      <th>1980-01-01 22:00:00</th>      <td>8.4240</td>    </tr>    <tr>      <th>1980-01-01 23:00:00</th>      <td>6.2529</td>    </tr>    <tr>      <th>1980-01-01 00:00:00</th>      <td>4.1499</td>    </tr>    <tr>      <th>1980-01-02 01:00:00</th>      <td>2.1834</td>    </tr>  </tbody></table>

**Comment by Sibada** [comment]
来自 魅族 MX4 Pro

-------- 原始邮件 --------
发件人：Joe Hamman <notifications@github.com>
时间：周六 10月10日 00:42
收件人：UW-Hydro/VIC <VIC@noreply.github.com>
主题：[VIC] BUG: Output timestamp is 24 hours off at midnight (#298)
