### ISSUE TITLE
Add support branch for 4.2.1 Irrigation code

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#300]
@bartnijssen  has asked that we add a support branch for @hydrotian's VIC 4.2.1 Irrigation work (https://github.com/hydrotian/VIC_4.2.1_irrigation).  We have a few questions to answer before we can create the branch.

1. The irrigation code is not on a branch that came from the main git repository (only 2 commits in history). So, do we want to maintain the history or should I just copy the code over to an empty branch?
2.  Was the original root of this repository actually 4.2.1 or did @hydrotian just copy over some pieces of the 4.2.1 repo? This is important for describing what the support branch really is.

**Comment by hydrotian** [comment]
For question 2. My impression is that the original root of this repository was VIC 4.2. Ted Bohn and Ingjerd Haddeland incorporated the irrigation scheme into the model and named it 4.2.1.

**Comment by tbohn** [comment]
All I know about this is that I sent my private code (based on 4.2) to
Ingjerd, who might have used some portion of my irrigation code in her
version (but I would not blame her if she didn't use my irrigation code -
it was pretty messy).  But presumably the branch point would be 4.2.

Ted

**Comment by jhamman** [comment]
Okay, but the directory and file structure in https://github.com/hydrotian/VIC_4.2.1_irrigation looks nothing like 4.2 so I'm not sure how to proceed.

**Comment by bartnijssen** [comment]
@Tbohn: Was there a specific reason to send your private version of the code? We are using git to establish a trail for source code modifications. It's an important step in ensuring reproducibility and thus a part of the scientific process. Sending people your private version of the code subverts this and is something I frankly find extremely frustrating.

@hydrotian and @tbohn : Please sort out between the two of you what the provenance of this code is. This is not for @jhamman or me to sort out. And ***PLEASE*** start using git the way it is supposed to. Your shortcuts are simply creating more work for others and I think it is a dangerous path to be on if you want to publish papers.

**Comment by bartnijssen** [comment]
@hydrotian: This is not optional. This code needs to be as a support branch on our github repo since it has been used as part of a paper. In the future I will no longer allow people in my group to submit a manuscript unless their code is under version control on our github site.

**Comment by bartnijssen** [comment]
@hydrotian: I just looked at your repo. The readme and the way you just plopped this into github as a "first commit" are wholly inadequate. Please take this serious, this is not a joke.

**Comment by tbohn** [comment]
I think I should clarify: I only gave my code to Ingjerd to show her what
I'd done, in case she wanted to use anything I'd written.  I was not part
of Ingjerd and Tian's project and I was not directly involved in their code
development.  It's their business how they present their code for inclusion
in the repo.

Ted

**Comment by bartnijssen** [comment]
@tbohn: Did you point her to your github repo or did you email her a tar file of code (or point her to your directory on disk)?

@hydrotian: Please figure out with Ingjerd where your code comes from. This needs to happen ***now*** as we may need to correct the proofs of the paper with regards to the model version.

**Comment by tbohn** [comment]
I created my private code outside of git.  I believe I sent her a tar file.

Now that I know better, I will use git for these purposes in the future.
Sorry if this has caused any problems.

Ted

**Comment by bartnijssen** [comment]
So please provide Tian with the provenance of your code: At what point did you split off from what version?

**Comment by tbohn** [comment]
Hi all,

The code I handed to Ingjerd and Tian was based on 4.1.2.k.  However, this
code included the veg_hist code that I later ported to 4.2.  So, it is
somewhat intermediate between 4.1.2.k and 4.2.

I apologize for any confusion this might have caused.  From now on, I will
use GIT to develop and share code.

Regards,
Ted

**Comment by hydrotian** [comment]
@bartnijssen @tbohn I apologize for this chaotic situation I created here. First of all, The VIC irrigation model used for the JHM paper was based on VIC 4.0.6, developed by Ingjerd about 10 years ago and it has been added to our VIC repo as a supporting branch about 2 years ago (https://github.com/UW-Hydro/VIC/tree/support/VIC.4.0.6.irrigation). Second, for the ISI-MIP project, Ingjerd modified Ted's private code earlier this year because it has the varying land cover feature in it, which is required by ISI-MIP project. The model was transferred as tar files through emails.

**Comment by tbohn** [comment]
If it's helpful to piecing this together, as I worked on my private code, I
ported fixes from 4.1.2 and 4.2 into my private code until I froze my code
and ported veg_hist into 4.2.  So, I think you'll find that the diff
between the source code of Ingjerd/Tian's code and the 4.2/src directory is
not super big - should primarily consist of the irrigation stuff plus
possibly a few of the later fixes to 4.2.

Ted

**Comment by bartnijssen** [comment]
@hydrotian : What dis we say was the VIC version in the JHM manuscript? Did we make is clear that that was 4.0.6. That would alleviate my immediate concern.

**Comment by jhamman** [comment]
@hydrotian - Since there is not really any history in your git repository, I recommend updating the `src/` directory in the `support/VIC.4.2.a.irrigation` branch that I just created and opening a pull request from your fork.

Please do not include any temporary files (e.g. `#get_global_param.c#`) or Make file objects (e.g. `.depend`).

Also in that PR, we should have:
- a thorough commit message describing the changes made, versions, etc.
- an update to the readme file.  Probably just add in the header that this is a support branch and you can cite your paper there.

Once that PR is open, we should have @tbohn and Ingjerd give things a review to make sure everything looks right.  It would be helpful if we could actually see the diff between these two sets of code.

Lastly, we may want to run a few short simulations with the updated branch to show that we can reproduce the results from your paper.

**Comment by bartnijssen** [comment]
@hydrotian : Please keep moving this forward, so we can close this asap.

**Comment by jhamman** [comment]
closed via #301
