### ISSUE TITLE
Fix OUTPUT_FORCE option in VIC 4.2

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#305]
The OUTPUT_FORCE option is broken in VIC 4.2 as a result of the new veg_hist code in initialize_atmos().  The new code in initialize_atmos() associated with the veg_hist feature assumes that the veg library and veg_parameter files have been read, and associated data structures populated.  But this is not the case for the OUTPUT_FORCE option.  This discrepancy needs to be resolved.

**Comment by tbohn** [comment]
Question: would it be acceptable to fix this issue by having VIC read the veg library and veg parameter file when running OUTPUT_FORCE?  This would mean that users who are currently running OUTPUT_FORCE without supplying a veg library or veg param file would now have to supply them.  But seems like most people who would be running VIC in OUTPUT_FORCE mode would have those files available for their domain anyway.

If this is acceptable, then the code changes for this fix are minimal and should be ready later today.

If not, then I'll have to add logic to disallow the possibility of mixing LAI_IN, ALBEDO, and VEG_COVER with the other forcing variables, since if they were to appear in the forcing file used by OUTPUT_FORCE, VIC would need to know how many columns they use even to skip them, which, in turn, would require reading the veg parameter file.  They'd have to be in separate input files, and I'd need to split the forcing variable lists into these two groups and handle them separately.  Could be time-consuming and error-prone.

**Comment by bartnijssen** [comment]
Requiring people to read info that is never used points to persistent design problems with the implementation of the `veg_hist` option. Given that the use of `veg_hist` is optional, there are way too many required changes for users that are not using this option (i.e. most of them). I much prefer the second option, which while more work for you, would appear to decrease the amount of work for almost anyone else. Discuss!

I would be amenable to the argument that we can a) remove the OUTPUT_FORCE option from 4.2 anyway or b) leave it as you suggest and people without a veg_lib and veg_param file can use the standalone generator that will be made in parallel with 5.0

**Comment by tbohn** [comment]
Thank you for giving me an argument that you're amenable to - I'll use it then :-)  I would lean towards option (b), which would affect the fewest users - only those who use VIC as a forcing disaggregator without ever intending to create/obtain veg lib/param files.  Do you have a preference between option (a) or (b)?

I apologize for the design flaw.  It was something that I didn't foresee.  It was important to me that we not follow the simpler (but inaccurate) approach of using a single timeseries of each of the veg_hist variables, applied to the entire grid cell.  At the same time, it was very appealing to use the same forcing variable array for these multi-dimensional variables as for the existing ones, so that we'd get the benefit of all of the forcing variable processing functions with relatively little modification.  But I forgot that some users might be using VIC as a forcing disaggregator without any veg lib/param files.

Although, given that veg lib/param files are required for running the full model, anyone who intends to run VIC will need those files eventually anyway.  So, I'd think that it would only be a relatively small number of users who would use VIC as a forcing disaggregator without intending to use the full model and therefore without intending to obtain/create veg lib/param files.

But you're right, we can't say for sure how many users we're talking about, and my change shifts the burden onto them.

**Comment by tbohn** [comment]
Looking at the docs, I see that I should also update the "VIC Disagg" page.  Not that it's technically incorrect - it doesn't explicitly say that users can leave the veg lib/param file information blank - but doesn't say what these should be set to, and if they're required we should mention their required values in this list.  Also, I see a couple of typos that need fixing.

**Comment by tbohn** [comment]
It just occurred to me, I could insert a few "if" statements that check whether LAI, albedo, or vegcover have been supplied as forcings.  If not, and OUTPUT_FORCE is true, then VIC could skip reading the veg lib/param files as before.  If we tell the users to *not* mix LAI, albedo, and vegcover with the other met variables, i.e. segregate them into separate files (which is probably what they'd be doing anyway since these variables have different sources), then when they run OUTPUT_FORCE, if they only supply the normal meteorological files, they won't experience any change in behavior.

What do you think?

**Comment by bartnijssen** [comment]
I think it would be fine to go for option b) and leave VIC itself alone ;)

**Comment by bartnijssen** [comment]
It just underscores that we (in general) have to think a bit more strategically when adding options and features. That does not just apply to you, but to all of us involved with VIC development. "Making it work" is only part of the story.

**Comment by tbohn** [comment]
True.  Seen this happen numerous times - a few of them my fault!

**Comment by jhamman** [comment]
closed via #307
