### ISSUE TITLE
Veg_hist code in 4.2 lacks an update

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#306]
I have discovered that my original implementation of the veg_hist feature in release 4.2 was missing a modification I subsequently made in my private version but forgot to add to GIT.  This modification results in minor changes to soil evaporation magnitudes but is necessary to make 4.2 match the results and description in my manuscript.  Changes are confined to two files: arno_evap.c and func_surf_energy_bal.c.

I'd like to add this as a hotfix to 4.2.  Would that be OK?

**Comment by tbohn** [comment]
The code changes for this are ready on my own branch off master, and I can make a pull request, but I don't know which official branch to make the pull request to.

**Comment by jhamman** [comment]
I think 4.2.c is fine.  I can backport to 5.  Make a PR against master.
