### ISSUE TITLE
VIC overwrites veg_lib values of LAI, albedo, and vegcover with those of the current cell

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#319]
The function read_vegparam() overwrites the values of LAI, albedo, and vegcover in the veg_lib structure with those from the veg_param file for the current cell, if they are listed there and if LAI_SRC, ALB_SRC, or VEGCOVER_SRC are set to FROM_VEGPARAM.

In olden times this was not a problem - the veg_lib structure's function was re-purposed to contain climatological values of LAI and albedo for the current cell.  However, the new veg_hist feature in release 4.2 allows for the values of LAI, albedo, and vegcover in the veg_param or veg_hist files to be -1 (the "nodata" flag for these quantities), which was intended to indicate to VIC that it should take the value from the veg_param file if "nodata" in the veg_hist file, or from the veg_lib file if "nodata" in the veg_param file.  The reason for this is that some global datasets of these quantities (e.g. MODIS products) have nodata values in some cells on some dates due to cloud cover or other poor retrievals.

Unfortunately, for this to work properly, we can't have VIC overwriting the veg_lib structure with the current cell's veg_param values.  If we encounter a cell for which some of these values are "nodata", VIC will use what's in veg_lib, which will be the veg_param value from the last cell that had a valid value.

To fix this, I propose we add some 12-element arrays to the veg_con structure, to store the values of LAI, albedo, vegcover, and Wdmax (which depends on LAI) of the current cell without overwriting the veg_lib values.  So, the veg_lib structure will essentially be a read-only copy of the veg_library file in memory.

I propose that this be included in the upcoming hotfix 4.2.c.

**Comment by tbohn** [comment]
Am I correct in assuming you'd prefer that I create my branch off of the official master, and that I should not include the contents of my other 2 (pending) pull requests?

Also, are my 2 pending pull requests waiting on me for anything?  Are they essentially approved or is there some chance you will want me to change something?

**Comment by jhamman** [comment]
branch off master and issue against 4.2.c.

@bartnijssen and I will take another pass through your other prs asap.

**Comment by jhamman** [comment]
@tbohn - responding to this issue.  I think we want to ovoid any time information inside `vic_run`.  In my opinion, the solution here needs to fill a single set of scalar veg params that go into `vic_run`.  However the driver decides to do that is up to the individual driver.

**Comment by tbohn** [comment]
This is just a fix to 4.2... I can find a different fix for 5.0...

**Comment by tbohn** [comment]
@jhamman - did you see my response to your comment?  Are we on the same page, that this is 4.2 and thus pre- veg_hist overhaul?  The overhaul I will do of veg_hist in 5.0 will obliterate any of the changes I make to 4.2.  I'm just trying to get 4.2 to work correctly.

**Comment by jhamman** [comment]
Okay @tbohn - I'm tracking with you.  I'll review #321 now.
