### ISSUE TITLE
Enable reading of veg_hist from netcdf files

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#325]
Need to add this capability to the image driver.  @bartnijssen and @jhamman I might want to discuss the structure of these files with you before I get started.

I suppose that the netcdf file would require a uniform number of "levels" in the veg class dimension across all grid cells.  Veg classes that aren't present would just have a missing/fill value.  Any other ideas?

It might also be worth revisiting how it's handled in ascii.  The way I've implemented it so far is to have a column for each veg tile.  This results in different numbers of columns per cell, and necessitates sending veg param information to the reading functions.  But it certainly saves space...  I'm not sure how else to do this other than having a column for every veg class in every file, and just use a missing value (nodata) in those columns for veg classes that aren't present.  This would simplify the VIC code but dramatically increase the size of the veg_hist files.  Any other ideas are welcome...

**Comment by tbohn** [comment]
You can assign this to me.

**Comment by jhamman** [comment]
closed via #359
