### ISSUE TITLE
Implement reading of lake parameters in 5.0 image mode

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#326]
Currently `vic_init()` contains just a placeholder for reading lake parameters.

**Comment by tbohn** [comment]
You can assign this to me.

**Comment by tbohn** [comment]
Just a heads-up: I'm currently working on this, should be finished in a day or so.

**Comment by bartnijssen** [comment]
@tbohn: The danger of adding time estimates to issues ....

**Comment by tbohn** [comment]
Actually, I finished the code shortly after that statement.  But yes, unforeseen issues intervened.  I thought testing the code would be much more straightforward.  I'm currently updating tonic to convert some ascii vic inputs that I have (including lake parameters plus new options) to netcdf.  Which I guess needs to be done sooner or later.

**Comment by jhamman** [comment]
closed via #388.
