### ISSUE TITLE
Need documentation (release 5.0) describing veg_hist inputs

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#329]
Need to add documentation (to release 5.0) for veg_hist inputs, similar to meteorological input files but optional.  Also need to make it clear that if these are used, their values will be taken instead of those from the veg_lib or veg_param files.

**Comment by jhamman** [comment]
Agreed, please include in https://github.com/jhamman/VIC/pull/8.

**Comment by tbohn** [comment]
I think this was addressed in the sync/4.2.c PR that's been merged by now.

**Comment by jhamman** [comment]
closed via jhamman#8 and #324
