### ISSUE TITLE
Memory leak due to double-allocation of some input vars in 5.0

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#334]
In alloc_atmos.c, carbon and lake input vars are double-allocated (two sets of calls to calloc).  This causes a memory leak.  Removing the extra allocations fixes the memory leak.

I have a fix prepared for this; will issue a pull request shortly.

**Comment by tbohn** [comment]
Actually, the pull request will wait on the sync/4.2.c pull request...

**Comment by tbohn** [comment]
cc-ing @jhamman and @bartnijssen

**Comment by jhamman** [comment]
sounds good @tbohn
