### ISSUE TITLE
Water balance errors in 5.0 classic

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#335]
I'm getting large cumulative water balance errors in 5.0 classic, in the development branch pre-sync/4.2.c.  I haven't finished investigating - there could be erroneous settings in my global parameter file.

Some important details: I'm using a veg_library file that contains vegcover values.  The veg_parameter file also contains LAI, vegcover, and albedo climatologies for each grid cell.  I am not reading in veg_hist forcing files however.

I will try some further tests with different global parameter file settings, to see if I can isolate the problem.

**Comment by tbohn** [comment]
cc-ing @jhamman and @bartnijssen

**Comment by jhamman** [comment]
@tbohn - I think I've seen this before, when debugging a few other issues.  I thought I had already raised an issue here but I can't find it now (so I probably didn't).  I never ran it down far enough to give much indication of what is going wrong.  Let us know if you find anything.

**Comment by tbohn** [comment]
OK, preliminary diagnosis is good: using a quick and dirty perl script to compute wb errors from the output files (I'm out of town right now and logging in via a telnet session) yields nearly 0 cumulative error for both VIC 4.2 and VIC 5.0 (3 different branches).  So it appears that the errors are simply the result of a bug in calc_water_balance_error() or put_data() rather than actual errors in fluxes or storages.  Which makes sense since we didn't really make major changes to the physics.

I'll post more when I know more.

**Comment by jhamman** [comment]
I bet the bug is in `put_data`, nothing really has changed in `calc_water_balance_error`.  There were some units changes in `put_data` so that could be it.

**Comment by tbohn** [comment]
After more testing, I realize that my earlier crude water balance check ran on the wrong files.  Re-running shows that, in fact, 5.0 does have water balance errors.  The errors are always equal to -evap.  Comparing results with those of 4.2, it appears that in 5.0, evap is not being subtracted from soil moisture.

Again, this is true of the develop branch pre-sync/4.2.c as well as post-sync/4.2.c.  I will focus on things like vic_run.c, surface_fluxes.c, runoff.c, etc. and will update you here when I have more information.

**Comment by bartnijssen** [comment]
That seems odd, since we did not mess with the physics. Is this a bug fix that was made in 4.2 that has not made it into 5/develop yet?

**Comment by tbohn** [comment]
No, there were no such water balance errors in 4.2 that needed any fixing...  Joe mentioned that he had seen water balance errors in 5.0 before but hadn't tracked them down.

Perhaps once I find the bug it will be clearer how it might have gotten into the code.

**Comment by tbohn** [comment]
Another weird thing I noticed: 5.0's max soil moisture storage comes out a little different than that of 4.2, for the same input parameters...  differing by 1-2 mm.  Not sure it's related to the water balance errors though.  I might need to open a new issue for this.

**Comment by tbohn** [comment]
@jhamman and @bartnijssen I believe I've found the cause of the errors.  In runoff.c, the old code was dividing the estimated evap by dt (which was in units of hours) in order to get evap per hour (= evap per runoff time step, as runoff calculation was at a time step of 1 hour).  The new version of runoff.c still divides evap by dt, but now dt is in units of seconds, reducing by a factor of 1/3600 the evap that would be subtracted from the layer moisture (yet leaving the original evap reported in the output unchanged).  This would explain why the layer moisture essentially doesn't change in response to evap, yielding wb errors nearly identical to -evap.  I think we ought to be dividing evap by runoff_steps_per_dt (which hasn't been calculated yet at that part of the code, so the calculation also needs to be moved up within the code) since evap is computed for model dt and needs to be rescaled to the runoff dt.

I'll try implementing/testing my proposed fix and see if it fixes the problem.

**Comment by tbohn** [comment]
That fixed the majority of the errors.  But now there are much smaller errors that occur only when precip > 0.  So, there is a second issue somewhere.

**Comment by tbohn** [comment]
...and this second bug was the same issue that I described with evap, but for dt_inflow.  Now all errors appear to be eliminated.

**Comment by jhamman** [comment]
:+1: :tada: 

Thanks for sorting this out @tbohn.

**Comment by tbohn** [comment]
Well, there's still some suspicious behavior that I'm looking into.  5.0 is computing slightly larger max moisture storage for the soil layers than 4.2 does - presumably these should be exactly the same given the same soil textures and thicknesses.  And 5.0's ET and Ra are different from 4.2, more than can be accounted for by the difference in max soil moisture storage.  So there may be a couple more bugs in there...  should I open a separate issue for these?

**Comment by jhamman** [comment]
@tbohn - 

I have a branch that may fix some of those.  Let me dig it up and I'll point you to it shortly.

**Comment by tbohn** [comment]
OK, thanks.  I am zeroing in on the soil layer max moist bug - it appears that layer thicknesses are ending up with an extra 0.0010 m being added to them in 5.0's read_soilparam.c.  Don't know the reason yet.  Did you see this and/or fix it in your branch?

**Comment by tbohn** [comment]
... And the reason for the extra 0.0010 m is that the code used to round the soil thickness (depth) to the nearest mm in 4.2 was not completely replaced by the round() function in 5.0.

4.2's code (paraphrased):
  depth = (float)(int) (depth * 1000 +0.5) / 1000;
The adding of 0.5 and then casting as (int) achieves rounding.

5.0's code:
  depth = round(depth * 1000 + 0.5) / 1000;

If round() is supposed to replace the crude rounding in 4.2, the addition of the 0.5 needs to be eliminated, as follows:
  depth  = round (depth * 1000) / 1000;

@jhamman I assume you'd like me to *not* include this fix in the same branch as the wb error fix, correct?

If so, I'll open a new issue and copy this explanation to it.

**Comment by jhamman** [comment]
@tbohn - Go ahead and leave it on this branch and just title your PR something like "fixing_5.0_bugs".

I'm not finding my branch and I'm not sure I had fixed much.  I do remember I was zeroing in on `read_soilparam.c` so this could be the bug we were hunting for.

**Comment by jhamman** [comment]
closed via #341
