### ISSUE TITLE
global.param.sample out of sync with code in 5.0

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#336]
global.param.sample has the following inconsistencies with the code:

1. `missing an entry for RUNOFF_STEPS_PER_DAY`
2. `contains unrecognized STARTHOUR option`
3. `contains unrecognized FORCEHOUR option`
4. `contains unrecognized MEASURE_H option`

**Comment by jhamman** [comment]
Yes, we need to overhaul the example global parameter file.

**Comment by jhamman** [comment]
closed via #342
