### ISSUE TITLE
Unable to *not* supply vegcover values in both veg_lib and veg_param simultaneously

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#337]
Not sure whether this is intentional or a bug.

At present, in VIC 5.0, we can't supply VIC with both veg_lib and veg_param files that don't contain vegcover values.  This is because the global option VEGCOVER_SRC can only be set to one of: FROM_VEGLIB or FROM_VEGPARAM.  If it's set to FROM_VEGLIB but the veg_lib file doesn't contain vegcover values (and VEGLIB_VEGCOVER accurately reflects this by being FALSE), VIC will exit with an error.

So, my question is: do we want to require users to supply vegcover values in the veglib?  They'll need new veglib files.  This is easy enough to do - it's a minor modification to the old NLDAS veg lib to add 12 vegcover values of 1.0 to each veg class, and that should theoretically allow users to reproduce old behavior.  If this is the way we want to go, then we should post a new version of the NLDAS veg lib for VIC 5.0 that contains these values.

Personally I'm fine with this solution and would prefer it.  But @bartnijssen and @jhamman  I need to know your opinions on this before I can propose a specific solution.

If we require vegcover values, I'd be happy to create a new NLDAS veg lib for the "samples" directory.

If we want to allow the users to not have anything to do with vegcover values, then we need to modify the logic in VIC that doesn't allow vegcover to be omitted from both veg_lib and veg_param files.  Could be a simple matter of initializing VEGCOVER_SRC to MISSING and then adding a case for MISSING that would set vegcover to 1.0 everywhere/all time.

**Comment by tbohn** [comment]
As per my conversation with @bartnijssen and @jhamman, here's what I'll do:
1. Add another allowable value for options.VEGCOVER_SRC that will denote setting all VEGCOVER values to 1.0 - maybe I'll call it "UNUSED" or "DEFAULT" - I'll see if there are any existing preprocessor definitions that I can use.
2. Actually, no other items in the list at this time...

**Comment by jhamman** [comment]
closed via #357
