### ISSUE TITLE
VIC 5.0 classic never skips forcing records

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#343]
VIC 5.0 classic never skips forcing records - the first record in the forcing file will be used on the first step of the simulation, regardless of the date/time that the simulation is supposed to start.

The variable global.forceskip[i] is supposed to contain the number of records of forcing file i to skip before storing them in the atmos[] array.  global.forceskip[i] is initialized to 0 (as in 4.2).  But the value of global.forceskip[i] is never computed.  In 4.2, the values are computed in make_dmy.c.  In 5.0, make_dmy.c was overhauled to use date2num(), but it appears that the overhaul omitted the section that computed global.forceskip[i].

**Comment by jhamman** [comment]
closed via #344

**Comment by tbohn** [comment]
This issue still appears to be open... but should be closed...
