### ISSUE TITLE
Code cleanup in 5.0 runoff.c

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#345]
These are mainly cosmetic issues but would help in future code maintenance:
1. Since we have removed the variable Tlayer_spatial[frost_area], we can remove the loop over frost areas that computes tmp_fract, since the only purpose of this variable was for computing Tlayer_spatial[].  We can also remove tmp_fract itself.
2. It looks like someone started to replace frost_area with fidx, but only completed one block of code.  So now there are two different variables with the same purpose in different parts of the code.  I propose replacing all other instances of frost_area with fidx and getting rid of frost_area.

**Comment by jhamman** [comment]
sounds good @tbohn.  Feel free to issue a PR for this.

**Comment by jhamman** [comment]
closed via #349
