### ISSUE TITLE
Wrong aerodynamic resistance values in 5.0

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#346]
This is due to a sloppy implementation of the sync/4.2.c (I am to blame).  The problem is in `surface_fluxes.c`, in which I created a new array `iter_aero_resist_veg[]` and attempted to copy the values of `iter_aero_resist_used[]` into it.  The problem is that `iter_aero_resist_veg[]` has 3 elements but `iter_aero_resist_used[]` only has 2 elements.  This led to overstepping the array bounds and getting weird values.

So, I propose to fix this.  It will require only minor modifications to `surface_fluxes.c`.

**Comment by tbohn** [comment]
Note that this bug doesn't exist in 4.2.c, since I implemented the sync/4.2.c slightly differently from 4.2.c.

**Comment by jhamman** [comment]
by all means, let's fix this.

**Comment by jhamman** [comment]
closed via #352
