### ISSUE TITLE
Need to update VIC 5.0 ReleaseNotes.md to include VIC 4.2.c

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#351]
Currently VIC 5.0's ReleaseNotes.md asserts that VIC 4.2.b is the final release in the 4.2 series, and does not describe any of the changes that went into 4.2.c.

**Comment by tbohn** [comment]
This was addressed by PR #330 :-)

**Comment by jhamman** [comment]
closed via #361
