### ISSUE TITLE
Unused parameters in CalcBlowingSnow.c

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#353]
There are several unused parameters in the functions sub_with_height, CalcSubFlux, and transport_with_height.  These generate warnings every time we compile.

**Comment by jhamman** [comment]
If you can figure out how to get rid of these warnings, by all means, go for it.  @bartnijssen and I have both tried and have given up.  see #https://github.com/UW-Hydro/VIC/issues/134.

This will require solver in `CalcBlowingSnow.C`.

**Comment by tbohn** [comment]
Oh, I see.  I tried searching through the issues with the search string CalcBlow but it didn't turn this issue up.  Perhaps it only searched the open issues?  I understand now - the solver was hardcoded to expect these variables.  Well, if it's going to be that involved, I don't have any more time to spend on it than you all did.  So, perhaps it's worth tabling this.

**Comment by jhamman** [comment]
Yes, let's table this again.
