### ISSUE TITLE
Forcing disaggregation-related variables not completely removed from 5.0

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#355]
At the very least, OUT_TSKC is still listed in vic_headers.py and OutputVarList.md.  It's worth doing a pass over all files to make sure no other variables are mentioned that were removed when MTCLIM was removed.

**Comment by jhamman** [comment]
Yes, let's remove `OUT_TSKC` and any other variables we missed when we removed MTCLIM.

xref: #288

**Comment by tbohn** [comment]
@jhamman I can fix this pretty quickly.  In fact, I'll prepare a PR in the next hour.

**Comment by jhamman** [comment]
closed via #466
