### ISSUE TITLE
Remove month information out of vic_run() 

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#358]
There are still a few instances in which the current month is used (mainly as an array index) in vic_run() to determine parameter values.  Ideally we can move all references to the current month (or date or record) outside of vic_run().

**Comment by jhamman** [comment]
:+1:

**Comment by tbohn** [comment]
@jhamman I think I can fix this issue very quickly.  Only 3 offending lines remain, and one of them only requires a simple substitution of one variable for another.  The other 2 are the displacement and roughness variables you and I discussed before.  I'd be happy to set up veg_var versions of these, along the lines of LAI and albedo, which would solve this whole thing.

**Comment by tbohn** [comment]
Note: dmy is used in a few other places in vic_run, and getting rid of those will take more effort since the use of dmy penetrates pretty far down.  dmy->month is used in canopy_evap() to access various veg_lib array elements and dmy->day_of_year is used in solve_snow() to determine if the the snowpack is in accumulation or ablation phase.  Many functions therefore have dmy in the argument list to pass it all the way down to canopy_evap().

**Comment by tbohn** [comment]
Another thing dmy->day_in_year is used for is in the call to compute_coszen().  This happens in 2 places, one in vic_run()->calc_Nscale_factors() and the other in vic_run()->surface_fluxes() in prep for the call to faparl().  These two instances are (a) redundant and (b) only invoked if CARBON is true.  I could create a veg_var or atmos element for coszen, compute it outside vic_run(), and pass to the functions that need it via vic_run().  Let me know if you would like me to do this.

**Comment by jhamman** [comment]
@tbohn - 

I think we follow the ideas you've suggested here. Specifically for the main occurrences of `dmy` in `vic_run()`. 

I don't think it is worth the effort at this point to remove the `dmy` strcut from `solve_snow` or `canopy_evap`. It seems like we're not going to completely get rid of `dmy` in `vic_run` before we release 5.0.  

However, I think calculating `cozen` in `vic_force` and adding it to the `atmos_struct` makes since.  I don't think we need to worry about the memory usage for forcing variables (especially in the classic driver).

**Comment by tbohn** [comment]
OK, will do.

**Comment by jhamman** [comment]
@tbohn - I'm going to leave this open and will move the *Milestone* to *somday*.  Thanks for taking care of the majority of this issue.

**Comment by bartnijssen** [comment]
Not clear what the remaining issue is. Can we close this one (since it was addressed at least in part) and open a new one that clearly states what the remaining issue is?

**Comment by tbohn** [comment]
I can open a new issue if you'd like.  The remaining unfixed issue is:

dmy is used in a few other places in vic_run, and getting rid of those will take more effort since the use of dmy penetrates pretty far down. dmy->month is used in canopy_evap() to access various veg_lib array elements and dmy->day_of_year is used in solve_snow() to determine if the the snowpack is in accumulation or ablation phase. Many functions therefore have dmy in the argument list to pass it all the way down to canopy_evap().

**Comment by tbohn** [comment]
I've opened a new issue to deal with remaining instances of dmy in vic_run() and subsidiary functions: #510

**Comment by jhamman** [comment]
Thanks @tbohn.
