### ISSUE TITLE
Implement read/write of state variables in image driver

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#367]
Lake state variables are not currently read from/saved to state files in the 5.0 image driver.

It also appears that reading any state variables - not just for the lake, but all state variables - from a state file has not been implemented for 5.0 image driver.  If I'm mistaken, please let me know.  Otherwise, I will open a separate issue for that.

**Comment by tbohn** [comment]
...and you can assign this to me, as I'm going to start working on it very soon.

**Comment by jhamman** [comment]
Correct @tbohn.  Let's just make this issue about getting the read/write of state files in the image driver (I edited the issue title). Two pieces here:
- **Read the initial state file.** This is slated to go here: https://github.com/UW-Hydro/VIC/blob/develop/vic/drivers/image/src/vic_restore.c#L55-L57
- **Write the final state file.** This is slated to go here: https://github.com/UW-Hydro/VIC/blob/develop/vic/drivers/image/src/vic_image.c#L125-L128

Let's work together to come up with some tests that insure bit-for-bit restarts. This is actually on my list of things to do for the CESM driver so I'm up for helping with this in anyway I can.

**Comment by tbohn** [comment]
OK, sure.  The lake parameter stuff is almost ready - need to test the new code now.  I'd like to finish that up before embarking on the state file stuff - is that OK?

If you'd like to set up a time to meet or skype about this, just email me.

**Comment by bartnijssen** [comment]
Thanks for doing this - bit-for-bit restarts should really be the requirement here. Something that VIC has never been able to do, but which is essential for a number of projects.

**Comment by tbohn** [comment]
@bartnijssen - looking at the existing vic_store() function, I see that you've put snow_bands in the outer loop, and veg_class in the inner loop.  Any particular reason for this order vs veg in the outer and band in the inner?  Classic state files are structured with veg in the outer loop...

**Comment by tbohn** [comment]
@jhamman I'll ask you the same question I asked Bart: in the netcdf state files, should we structure the data as currently written in vic_store(), namely, bands in the outer loop and veg in the inner loop, or make it consistent with the classic driver files, namely, veg outer / bands inner?

Internally, VIC stores the data first by veg, then by band, so the classic driver state files are consistent with this.  I wrote the tonic statefile code to structure the state files the same way.  So, I'm tempted to change vic_store() to have veg outer / bands inner.  But before I do that, I want to make sure that there isn't some special reason why they're structured the other way in vic_store().

**Comment by bartnijssen** [comment]
We should optimize it so that the read is fastest (read one spatial slice at a time I think)

**Comment by bartnijssen** [comment]
There is no particular reason for the state files from the different drivers to be entirely consistent. It would be nice, but classic is ASCII and image is netcdf, so that will differ anyway.

**Comment by tbohn** [comment]
OK, thanks.  But why wouldn't a veg outer loop also be a single spatial slice at a time?  Either way, for each combination of veg and snowband, there is a spatial slice...

**Comment by tbohn** [comment]
A different issue: I'm having tonic write things like gridcell and mask to the state file (similar to the parameter file).  I realize that VIC may not need those variables but someone analyzing the file might want those handy.  If you all have no objections, I will also have vic_store() write those to the state file.  vic_restore() need not read them in.

**Comment by jhamman** [comment]
:+1: At some point, we need to write some checks that the coordinates and mask match between all these files. This will help with that.

**Comment by tbohn** [comment]
I also see that longer, more descriptive variable names have been used.  I'm continuing along those lines - I've changed the names of some of those in vic_store(), and I will be changing all the variable names in tonic to match them.

**Comment by tbohn** [comment]
@jhamman or @bartnijssen - while looking into storing arrays of lat and lon in the state files (I found how to do that), I tried to find where soil_con.lat and lng are assigned in image mode, and found only an initialization of them to 0.0 in init_library().  Are soil_con.lat and lng simply never assigned values in image mode, or did I miss something?

They are used in the carbon code, so they need non-zero values. If they aren't assigned already, I'll add an assignment somewhere (I'll open an issue for this).  Just let me know if you have any objections.

**Comment by tbohn** [comment]
More broadly:
1. (Assuming you're on board with reading lat/lon from the param netcdf file and storing in soil_con) Can we require lat and lon variables in all netcdf files?
2. Given that vic allows for either 1-d or 2-d versions of lat and lon in the output files, should we enable this choice in all netcdf files too?  If so, should they be required to be the same across all files, or allow to differ (and deduce this from the number of dimensions they have in the file)?  Note: tonic currently creates both 1-d (lat and lon) and 2-d (lats and lons) versions of the variables.  Probably not necessary, right?  Should I update tonic?  Or should both versions be required in all netcdf files (and we can eliminate the option for choosing the dimensionality of lat and lon)?
3. Tonic stores the variables 'gridcell', 'run_cell', and 'mask'.  I can 'gridcell' might be completely unnecessary within VIC, so I am happy to ignore it.  'run_cell' is the 0/1 flag - again, seems unnecessary, but makes me wonder if tonic should only write cells with 'run_cell' == 1 to the netcdf files, and 'run_cell' should not be included in the netcdf files.  I'm not sure how 'mask' differs from 'run_cell'.  Do we need to worry about this in either tonic or vic?

**Comment by tbohn** [comment]
Just to follow up: I'm leaning towards not having VIC read or write the 'gridcell', 'run_cell' or 'mask' variables, and I'm guessing you (@jhamman and @bartnijssen) are also.  I propose still having tonic write those variables for comparison with the ascii inputs, but having VIC ignore them.

**Comment by tbohn** [comment]
While we're at it, I see in vic_init() that the dstart and dcount indices are set using the global_domain structure.  Yet, then assignment to soil_con and other structures loops over i from 0 to local_domain.ncells_active.  I'm not sure what the difference is between global and local domains, but if they differ at all, it seems that the code will not have the desired effect (wouldn't you want to have dstart and dcount have an offset and length determined by the local domain?).  I'm bringing this up because I don't know whether to assign the local or global version of location[i].latitude/longitude to soil_con, but it seems to be a more broadly relevant question...

**Comment by tbohn** [comment]
Regarding the lat/lon coordinate variables: I'm just going to assume that the forcing, params and state netcdf files follow the same convention as the output results and state files, namely, COORD_DIMS_OUT determines their dimensions and DOMAIN_LON/LAT_VAR determine their names.  If you have any objections, please let me know.

**Comment by jhamman** [comment]
Ted, catching up on your comments here:

re. https://github.com/UW-Hydro/VIC/issues/367#issuecomment-198621008:  Yes, lets use dimension names that are meaningful.  They do not have to match those in the C source code.  In fact, giving the abbreviated nature of the variables in C, I'd say let's try to create self describing variables for the state files (e.g. `moist` --> `soil_moisture`)

re. https://github.com/UW-Hydro/VIC/issues/367#issuecomment-198784402:

>  Are soil_con.lat and lng simply never assigned values in image mode, or did I miss something?

I think you're right.  In the image driver, we use the domain structure to track location.  For the carbon code to work, you'll need to fill the lat/lon variables in the `soil_con` structure from the `local_domain`.

re. https://github.com/UW-Hydro/VIC/issues/367#issuecomment-198786557: 

> 1. (Assuming you're on board with reading lat/lon from the param netcdf file and storing in soil_con) Can we require lat and lon variables in all netcdf files?

Yes.  The domain, parameters, history, and state files should all be cf-complaint. Its not a bad idea to say that all these files include the following meta-variables:
- lat (yc for 2d)
- lon (xc for 2d)
- mask

This will allow us to consistently check that all files exist in the same model domain.

> 2. Given that vic allows for either 1-d or 2-d versions of lat and lon in the output files, should we enable this choice in all netcdf files too? If so, should they be required to be the same across all files, or allow to differ (and deduce this from the number of dimensions they have in the file)? Note: tonic currently creates both 1-d (lat and lon) and 2-d (lats and lons) versions of the variables. Probably not necessary, right? Should I update tonic? Or should both versions be required in all netcdf files (and we can eliminate the option for choosing the dimensionality of lat and lon)?

Let's deduce the dimensionality of the coordinate variables in VIC and update tonic to write the minimum number of dimensions possible.

> 3. Tonic stores the variables 'gridcell', 'run_cell', and 'mask'. I can 'gridcell' might be completely unnecessary within VIC, so I am happy to ignore it. 'run_cell' is the 0/1 flag - again, seems unnecessary, but makes me wonder if tonic should only write cells with 'run_cell' == 1 to the netcdf files, and 'run_cell' should not be included in the netcdf files. I'm not sure how 'mask' differs from 'run_cell'. Do we need to worry about this in either tonic or vic?

- `grid_cell` is likely not used in the `image` driver, but it is in `cesm`.
- `mask` is typically a land/sea mask, while `run_cell` is a hold over from VIC 4, where you could turn on/off cells in the soil parameter file. I think they are sufficiently different to warrant keeping them both.  For most applications, they will match, but they don't have to. 

re. https://github.com/UW-Hydro/VIC/issues/367#issuecomment-198810408: 

> Regarding the lat/lon coordinate variables: I'm just going to assume that the forcing, params and state netcdf files follow the same convention as the output results and state files, namely, COORD_DIMS_OUT determines their dimensions and DOMAIN_LON/LAT_VAR determine their names. If you have any objections, please let me know.

No objections for now. Let's see how it all comes together and we can iterate on the best solution if necessary.

**Comment by tbohn** [comment]
Thanks @jhamman - I'll look into reading/processing gridcell, run_cell, and mask from vic_init() and writing it into all output and state files.  Depending on how involved it is, I might put that into a separate issue, for expediency's sake, if that's OK.  I need to wrap up my coding today and attend to some other things.  I'll have opportunities to continue working on VIC later this week, but I don't want to hold up the group development/testing.  Also, it seems to me from from the point of view of organizing PRs along the lines of "atomic" features, it would make more sense to have a separate issue and PR for handling run_cell, mask, etc in all of vic's i/o, not just state files.

**Comment by tbohn** [comment]
Yet another question: any objections to my renaming vic_restore() to vic_restart() and creating a new vic_restore() that does the reading of the initial state file?  vic_restart() would be the analog of vic_start() in that it calls several functions needed to restart vic, and vic_restore() would be one of them.

**Comment by jhamman** [comment]
sounds fine to me.

**Comment by tbohn** [comment]
Which parts of what I asked - all of it?

**Comment by jhamman** [comment]
- yes to atomic features in your PRs
- yes to renaming `vic_restore`
- yes to using the same naming convention as the `classic` driver.

**Comment by bartnijssen** [comment]
Hold on - I would like to see an explanation of the `vic_restore` rename, because as described it sounds like there will now be a `vic_restart` that overlaps functionality with `vic_start`. That is not what we want. `vic_start` should always be called and `vic_restore` is already mentioned to simply restore the state, so I am concerned that there will be duplication of functionality. Please elaborate before going there.

**Comment by tbohn** [comment]
No worries.  I won't overlap/change functionality.  However, I see your point, since what I was proposing to call vic_restart() would be called from vic_start(), leading to new confusion.

How about this:

- Rename vic_restore() to vic_populate_state() - this name has no connotations regarding how the state is populated (as opposed to vic_restore(), which seems like the opposite of vic_store()).
- vic_populate_state() won't have any change to its functionality - it will still read the first forcing time step, optionally read an initial state file, and call initialize_model_state()
- Call the function that reads the initial state file read_model_state()
- Rename vic_store() to write_model_state()

**Comment by bartnijssen** [comment]
The whole point was that `vic_store` and `vic_restore` would be counterparts that do the opposite. Let's discuss this in person at the VIC5 meeting tomorrow. We can throw these comments up on the screen and look at the code to make a decision.

**Comment by tbohn** [comment]
OK, just for the record, for me the crux of the problem is that "restore" implies that a state previously existed (was written to a file by vic_store) and should be read back in.  So, "vic_restore" should not be the name of something that might create a new state from scratch as with a cold start.  That's all I'm sayin'.

**Comment by bartnijssen** [comment]
Yep - I fully agree. I had originally envisioned that there would be a tool in tonic that would allow one to create an initial state if one did not exist. I don't like how VIC currently implicitly creates a state if there isn't one. It hides the user's responsibility to create a plausible initial state and leads to spinup problems for users who are not aware of what the initial state is. So you would always call `vic_restore` and never create a default initial state from within VIC. If we do not want to go that route, then I think there should be a `vic_restore` or a `vic_create_state` (or something like it) and we call one or the other.

**Comment by tbohn** [comment]
OK, fair enough, I agree with that too.  So, let's modify my previous proposal:

- Rename the current vic_restore() to vic_populate_model_state()
- Name the new function that reads initial model state: vic_restore()
- vic_store() won't change name
- At present, the creation of a new model state from scratch is handled in initialize_model_state().  But I can open a new issue to request that the logic for creating a new model state be moved into a new function called vic_create_state().  That way it won't hold up implementation of state file i/o.

**Comment by tbohn** [comment]
Re: global and local domains - I now see that get_scatter* and gather_put* handle the mapping between global and local domains.

**Comment by bartnijssen** [comment]
Yes - you should handle this exactly the same way as reading any slice of data and let the `get_scatter_*` and `gather_put_`* handle the distribution behind the scenes. Anything else will pretty much not make it through code review.

**Comment by tbohn** [comment]
Yes - no worries, I have done that (except in a couple of cases in which I was dealing with non-geographic arrays that didn't need that).

My comment was referring to an earlier question I had about why the dstart and dcount values were relative to the global domain, while the looping over elements of dvar[] was relative to the local domain.  The reason is that the get_scatter* functions did the mapping and returned a dvar[] array covering the local domain.

**Comment by bartnijssen** [comment]
Ah yes - indeed!

**Comment by jhamman** [comment]
closed via #402
