### ISSUE TITLE
better name for vegcover?

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#382]
The veg parameter "vegcover" denotes the area fraction of a given veg tile that is covered by plants (as opposed to exposed soil between the plants).  But "vegcover" sounds similar to the definition of Cv (the area fraction of a veg tile) and the exposed soil sounds similar to a bare soil tile, leading to some confusion.  My attempts to make the difference clear in the comments describing the variables result in long descriptions.

I'm wondering if it might help to change the name of this variable to something like "fcan" (= canopy coverage fraction).  The exposed soil between plants could be viewed as gaps in the canopy.  My one reservation about this term is that users may associate a canopy more with forest (i.e., overstory) and less with low-lying vegetation.  Any opinions?

**Comment by bartnijssen** [comment]
YES (this has confused me a number of times already): :+1: 

`fcan` is fine with me, although a longer and less cryptic name would be preferred.

**Comment by tbohn** [comment]
How about fcanopy?

**Comment by bartnijssen** [comment]
:+1: (as you can tell I have discovered the thumbs up sign in github - just copying the cool kids)

**Comment by jhamman** [comment]
`fcanopy` sounds good.

**Comment by tbohn** [comment]
More details: this should involve:
1. change all instances of the variable name "vegcover" (or "VEGCOVER") to "fcanopy" (or "FCANOPY")
2. change comments/descriptions in source code to use the term canopy cover fraction instead of partial vegetation cover fraction, etc.
3. change documentation in the same way

**Comment by jhamman** [comment]
closed via #388.
