### ISSUE TITLE
Have 5.0 image driver use a single file handle for parameters

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#386]
The classic driver stores parameters in different files: soil, snow, veg, veg_lib, lake.  This makes sense because they are all ascii and have different data structures.

Netcdf files can accommodate heterogeneous structures more easily, so it makes sense to put all parameters in a single netcdf parameter file.  This would only necessitate a single file handle for the parameter file, instead of 4 or 5 as currently done.  However, making this change for the image mode would necessitate moving the definitions of filenames and filepointers structures into separate driver-specific .h files, and moving their initialization into driver-specific functions.

**Comment by jhamman** [comment]
I think it makes sense to have each driver use a custom structures for file names and file pointers. I'm happy to take this on as it has to do with #380 and #381.

**Comment by jhamman** [comment]
closed via #547
