### ISSUE TITLE
Move default initial state creation to a separate function

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#401]
Currently, initialize_model_state() creates a default initial state when no initial state file has been supplied, in addition to various processing of state variables (e.g. variables that are derived from others).  The logic for creating the default initial state could be moved to a separate function, for cleaner,better organized code.

**Comment by jhamman** [comment]
@tbohn - was this done in #402 ?

**Comment by tbohn** [comment]
No.  Still needs to be done.  I assume it can wait until 5.1?

**Comment by tbohn** [comment]
Addressed in PR #464
