### ISSUE TITLE
TESTING: Results match between drivers

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#410]
Add a series of tests that check that the `Classic`, `Image`, and `CESM` drivers all produce the same results when run with the same set of forcings and settings.

cc @dgergel 

xref: #196

**Comment by jhamman** [comment]
closed via #576

**Comment by bartnijssen** [comment]
@jhamman : This was closed. Does that mean that the drivers actually match results or that we have written the tests to check this. If only the latter, it would be good to add an issue to confirm that the results actually match. This may need to be an umbrella issue with all remaining tests before the 5.0.0 release and then a separate issue for each test: image <--> classic, spatial runs for image, etc.

**Comment by jhamman** [comment]
@bartnijssen - This can stay closed.  Here are a few plots that demonstrate the model drivers are behaving identically (grid cells selected at random).  There is also a system test that @yixinmao wrote.

![out_sensible_48 3125_-120 6875](https://cloud.githubusercontent.com/assets/2443309/17788346/15f3a814-6542-11e6-971a-5738468bd9cd.png)
![out_lwnet_48 3125_-120 9375](https://cloud.githubusercontent.com/assets/2443309/17788355/1d925a8e-6542-11e6-94ec-22b76ed68a05.png)
![out_snow_surf_temp_48 3125_-120 6875](https://cloud.githubusercontent.com/assets/2443309/17788365/254fa2a4-6542-11e6-9632-d9dc3f893ccd.png)
![out_soil_temp_1_48 3125_-120 9375](https://cloud.githubusercontent.com/assets/2443309/17788368/2b16922e-6542-11e6-9e03-c78c78396099.png)
![out_swe_48 4375_-120 6875](https://cloud.githubusercontent.com/assets/2443309/17788376/33dac894-6542-11e6-9c89-3abc13a77218.png)

**Comment by bartnijssen** [comment]
OK - thanks - in general I like the idea of attaching plots to some of these test issues.
