### ISSUE TITLE
Incorrect albedo reported over lakes

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#419]
VIC's internally-used albedo over lakes is fine.  But it isn't being reported correctly in output files.  This won't affect results in any way (except for reported albedos).  The fix is trivial - a one-liner.

**Comment by jhamman** [comment]
So is the problem in `put_data` or somewhere in `vic_run`?

**Comment by tbohn** [comment]
It's in vic_run, in lakes.eb.c.

**Comment by jhamman** [comment]
Okay, let's fix this for 5.0, but after we have the test suite put together so we can demonstrate the change.

**Comment by tbohn** [comment]
Sure.

**Comment by tbohn** [comment]
This was addressed in PR #425 and can be closed
