### ISSUE TITLE
Inappropriate choice for default initial soil temperature in absence of initial state file

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#424]
Currently, the default initial soil temperature in the absence of an initial state file is set to the air temperature of the first time step.

A better choice (closer to equilibrium) would be soil_con.avg_temp, as long as this has been supplied.  This would reduce the amount of time necessary to spin up to a usable initial state.  This would also provide a potential solution to the TBD in vic_populate_model_state().

**Comment by jhamman** [comment]
Naive question: would it be possible to remove any dependence on the first timestep of met forcings? If so, this would be idea of the CESM driver where we don't get the first timesteps forcings during initialization.

**Comment by tbohn** [comment]
Not naive at all.  If the annual average soil temperature is supplied in the soil parameter file (which is required as the bottom boundary condition for the full_energy case) then we can use that to initialize soil temperatures.  All we need to do is modify the logic in read_soilparam() and vic_init() to require annual average soil temperature to be supplied if an initial state file is not supplied.

Obviously requiring an initial state file for all simulations in the first place would eliminate this problem.  However, for now, this would solve the immediate problem.  And I still feel that we should let the ability to choose default initial states remain as a vic feature, since vic already has all the information needed to make such a choice.  But I realize that I will likely be out-voted on that one.

Anyway: here's what I propose:
1. modify the logic in read_soilparam() and vic_init() to require average annual soil temperature if an initial state file hasn't been supplied OR if FULL_ENERGY is true (OR if LAKES is true).
2. initialize soil (and lake) temperatures to soil_con.avg_temp in the absence of an initial state file in initialize_model_state() (and initialize_lake()).
3. eliminate surf_temp as an input argument to initialize_model_state() (and initialize_lake()).

**Comment by jhamman** [comment]
closed via #464
