### ISSUE TITLE
documentation required for new debug branches

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#438]
`xxx_debug` branches were created, where `xxx` is `(master | debug)`.

The purpose of these branches is to add debugging code that we do not want in the production versions. 

Contributions would be the same as for any other code (go through code review if you want to get it accepted in `develop_debug` or `master_debug`). *_The main rule is that you cannot change state or flux values in the debug code._* So you can compare, assert, print, write to new files, calculate derivative values, etc. but you cannot modify any of the states or values (because then `_debug` results no longer match those from the corresponding branch).

The workflow would be :
* merge changes to `xxx` into `xxx_debug`
* add additional debug code into `xxx_debug`
* run tests with `xxx_debug`
* fix errors in `xxx`
* create PR for `xxx`
* once PR is accepted go back to top

Some code and checks from the `xxx_debug` branches may eventually be moved back into `xxx`.

**Comment by bartnijssen** [comment]
@jhamman : I still like this idea, but we never actually used any of this as far as I can tell. If it's not useful we could just close this and remove the `xxx_debug` branches (if they were even created).

**Comment by jhamman** [comment]
I think closing this sounds good.  I think the branches were created but never used.
