### ISSUE TITLE
bug report: error in vegetation parameter(LAI, albedo, etc) initialization when VEGPARAM_LAI=FALSE

### ISSUE THREAD

**Issue by pengbinpeluo** [UW-Hydro/VIC#455]
Hi Joe, 
I'm afraid that I have found another bug in the released version 4.2.c. When "options.VEGPARAM_LAI" is FALSE, the model will give biased albedo output since the vegetation albedo is not initialized in [read_vegparam.c.](https://github.com/UW-Hydro/VIC/blob/master/src/read_vegparam.c) To fix this bug, the following lines in [read_vegparam.c ](https://github.com/UW-Hydro/VIC/blob/master/src/read_vegparam.c)should be moved out of the "if ( options.VEGPARAM_LAI )":

>       for ( j = 0; j < MONTHSPERYEAR; j++ ) {
        temp[i].albedo[j] = veg_lib[temp[i].veg_class].albedo[j];
        temp[i].LAI[j] = veg_lib[temp[i].veg_class].LAI[j];
        temp[i].vegcover[j] = veg_lib[temp[i].veg_class].vegcover[j];
        temp[i].Wdmax[j] = veg_lib[temp[i].veg_class].Wdmax[j];
      }

Regards, 
Bin Peng(112233pengbin@163.com or pengbin@radi.ac.cn)

**Comment by jhamman** [comment]
Thanks for the report.  I'm cc'ing @tbohn since he knows this section of the code best.  

@pengbinpeluo - would you be willing to submit a bug fix pull request for this?

**Comment by tbohn** [comment]
Yes, I see what @pengbinpeluo is referring to.  I think the fix should be: move lines 242-247 to immediately before line 217.

**Comment by pengbinpeluo** [comment]
Hi Joe and Ted, I have submitted a bug fix pull request for this issue. Cheers!
