### ISSUE TITLE
ENH: Remove ALMA input/output options

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#486]
The ALMA unit convention is only partially supported by VIC 4 and its inclusion in VIC complicates the handling of units, especially for output variables. 

In VIC 5.0, we should only support a single set of units CF complaint whenever possible. This issue is proposing the removal of the ALMA units.

After #443 is completed, users will be able to specify any units they see fit using UDUNITS. This is scheduled for 5.1.

**Comment by bartnijssen** [comment]
Agreed - remove ALMA

**Comment by jhamman** [comment]
closed via #486
