### ISSUE TITLE
Potential typo in vic_run() call to water_balance()

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#497]
Currently, line 478 of vic_run.c calls water_balance() (part of lake model) and one of the arguments in the call is *veg_con.  Within vic_run(), veg_con is an array of structures, one per veg tile, so *veg_con doesn't quite make sense (I think it evaluates to veg_con[0]).  But water_balance() is expecting the veg_con structure that corresponds to the veg_tile that actually contains the lake, which might not be veg_con[0].  So it looks like a typo.

The fix would be simple: replace *veg_con with veg_con[iveg] in the call to water_balance().  it just needs to be tested to make sure this works correctly.

**Comment by bartnijssen** [comment]
Fixed per PR #498
