### ISSUE TITLE
Add sample VIC input/output dataset to archive

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#50]
We currently have a small sample dataset posted on the vic website for people to download and play with as an example.  One reason for adding this to the archive could simply be because when people download the model source code, it's nice for them to just get the sample dataset with it.

Another reason would be because different VIC versions require different parameters and/or different formats for the input files.  It would be good to be able to tag these and associate them with the version of the model that they correspond to.

Theoretically, this could be extended to archiving the inputs (and even outputs) of various projects.  But I'm leaning away from that - it could take up a lot of space and wouldn't really lend itself to incremental deltas.  It's probably best just to publish them elsewhere and make a note of the exact VIC version that worked with them.  Perhaps the way to handle this is: if you archive a version of VIC (like my dissertation work) on a support branch, you should archive a small set of sample inputs (e.g., veg library, global parameter file with the various options visible, one cell's worth of soil, veg, etc. parameters and forcings and states) along with it?

**Comment by jhamman** [comment]
closed via #387
