### ISSUE TITLE
TESTING: add MPI test to system tests 

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#508]
Extension of #506. 

In PR #506, we added functionality to run VIC using MPI. We should extend this to include a system test to check that running VIC using MPI on multiple processors produces the same results as running VIC on one processor.

**Comment by bartnijssen** [comment]
@dgergel : Please provide a detailed description of an issue in the body of the issue rather than using ultra-long titles and then no content.

**Comment by jhamman** [comment]
closed via #567
