### ISSUE TITLE
Replace hardcoded limits for tmpTshape and tmpZshape

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#511]
Currently limits for `tmpTshape` and `tmpZshape` are hardcoded in 

./drivers/shared_all/src/compute_derived_state_vars.c
./drivers/shared_all/src/generate_default_state.c
./vic_run/src/frozen_soil.c

At least two of these could be changed : `MAX_LAYERS --> options.nlayers` and `MAX_NODES --> options.nodes` since that is the actual size of the useful array. 

However this may be more work than it's worth.

**Comment by yixinmao** [comment]
This issue is addressed in PR #509
