### ISSUE TITLE
Memory leaks round 2

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#513]
This is a follow-up issue to #463.  Most of the memory leaks from that issue have been resolved, and it was getting difficult to see which issues remained.  The remaining ones are:

Image Driver:
get_nc_field.c: 44, 124
get_nc_dimension.c: 42

These are puzzling, as the functions they appear in do an `nc_open`, then query the nc filehandle for specific information, and then do an `nc_close`.  On the surface it looks like all memory allocation and freeing is handled by the netcdf library functions and that all memory allocated would be freed again by the `nc_close()` call.  But perhaps further investigation will reveal the cause.

**Comment by bartnijssen** [comment]
Discussion copied to and continued under #463
