### ISSUE TITLE
RELEASE: Final steps for VIC.5.0.0 release

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#589]
We don’t have any code changes to go into the final release of 5.0.0 but there is a bit to do still in terms of testing and documentation. Of course there may be a few code changes as a result of bugs we may uncover.

A list of all issues with the 5.0 milestone:
https://github.com/UW-Hydro/VIC/issues?q=is%3Aopen+is%3Aissue+milestone%3A5.0

Once this list is empty, we should be ready to release. I changed the target date for the release to September 1. Let's see if we can make that.

General discussion about release 5.0.0 can be captured under this issue.

**Comment by jhamman** [comment]
Here's my [checklist](http://vic.readthedocs.io/en/develop/Development/ModelDevelopment/#release-roadmap) for tomorrow's release:


- [x] Identification of features and fixes to be included in the release. This is coordinated through the VIC github page. **Done: see [5.0 Milestone](https://github.com/UW-Hydro/VIC/milestone/2)**
- [x] Features and fixes are added to the appropriate branch (develop or hotfix) via Github pull requests.  **Done: see list of closed issues and changelog**
- [ ] The model is tested using the VIC test framework. Each of the following tests should be run and verified for any release.
        - [ ] Unit tests
        - [ ] System tests
        - [ ] Example tests
        - [ ] Science tests
        - [ ] Release tests
- [x] Once all tests have been run and the release is ready, a few minor changes need to be made to the source code prior to a release (see https://github.com/UW-Hydro/VIC/pull/624):
  - [x] Update the version string for classic and image drivers (vic_version.h)
  - [x] Update the version string for the python driver (setup.py)
  - [x] Update the documentation. At a minimum this means updating ReleaseNotes.md.
- [ ] Make the release!
  - [ ] Merge the release branch into the master branch.
  - [ ] Create the tag. This is best done on the command line as git tag -f -a VIC.5.1.2 -m 'release tag of VIC 5.1.2, bug fix update for this example.
  - [ ] Publish the release on Github.
  - [ ] Update the VIC documentation and Readme files with the releases Zenodo DOI (e.g. DOI).
  - [ ] Update the develop branch with the changes from the master branch.
  - [ ] Reset the version strings in the develop branch.
