### ISSUE TITLE
DOC: Review and update VIC 5.0.0 documentation

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#590]
Update the documentation.

@helgason : review documentation from a “new user” perspective

For all of us: Please don't just point out problems, but if you know the answer, please fix the documentation directly and issue a PR against develop.

**Comment by jhamman** [comment]
I've made my pass through the documentation (#600). One additional todo was opened (#599) and I think @yixinmao said she would take care of it.

**Comment by bartnijssen** [comment]
@yxinmao, @dgergel, @jhamman, @hhelgason : Where is this at? Can we close this yet?

**Comment by jhamman** [comment]
Yes, this can be closed.
