### ISSUE TITLE
TESTING: Large-domain release tests

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#591]
Release tests.  

We haven’t really run the image driver on anything except the Stehekin 10-day test case. We have three larger domains that we should test on before VIC 5 is released:

 * Livneh 2015 - @yixinmao is going to take point here.  @jhamman has already generated 3hrly forcings and parameters

 * Global 0.5 deg - @dgergel has run this but ran into some errors. She should be able to wrap this up quickly.

 * RASM (image driver) - @jhamman ran this a few months ago but we’ve made lots of changes since so he should revisit this test case.

**Comment by bartnijssen** [comment]
We are we at with these tests?

**Comment by jhamman** [comment]
I have run and analyzed the RASM release simulation using the following specification:

- Forcings: Sheffield 2006, 3-hourly
- Simulation Dates: Cold start, 1948-1951
- Specs: Full-energy, frozen-soil w/ 25 thermal nodes

### SWE
![out_swe](https://cloud.githubusercontent.com/assets/2443309/18214410/cd824948-7101-11e6-9e88-394d4172a4f1.png)

### Albedo
![out_albedo](https://cloud.githubusercontent.com/assets/2443309/18214414/d3116a56-7101-11e6-8a5c-46be14169071.png)

### ET
![out_evap](https://cloud.githubusercontent.com/assets/2443309/18214419/d8c2686a-7101-11e6-9236-446c5255cc27.png)

###  Runoff + Baseflow
![out_runoff_tot](https://cloud.githubusercontent.com/assets/2443309/18214428/e121332e-7101-11e6-8f7f-d26423d06ced.png)

### Soil Temperatures
![out_soilt](https://cloud.githubusercontent.com/assets/2443309/18214439/ea5dc9d4-7101-11e6-8a4f-fab2df4f05ba.png)

**Comment by dgergel** [comment]
I have run and analyzed the global 0.5 degree simulation with the following:

- Forcings: CRUNCEP 6-Hourly 
- Domain: Global 
- Simulation Dates: Jan 1, 2006 - Dec. 31, 2009
- Specs: Full-energy (and water balance, only full energy results shown)
- Cluster: Hyak
- Nodes: 2 
- Processors: 16/node, 32 total 

Mean Annual Evaporation 
![image](https://cloud.githubusercontent.com/assets/5017308/18215295/641b4e38-7105-11e6-84a9-77052a0fec07.png)

Mean Annual Runoff (runoff + baseflow)
![image](https://cloud.githubusercontent.com/assets/5017308/18215316/747c29be-7105-11e6-88b2-11b805294183.png)

Mean Annual Snowfall
![image](https://cloud.githubusercontent.com/assets/5017308/18215325/830aac80-7105-11e6-8cc1-93012bea0a16.png)

Mean Annual Soil Temperature (surface layer)
![image](https://cloud.githubusercontent.com/assets/5017308/18215334/8ea25be2-7105-11e6-9422-9db13f989c41.png)

Summer Soil Moisture (JJA)
![image](https://cloud.githubusercontent.com/assets/5017308/18215343/9941644e-7105-11e6-920e-8a8881024057.png)

**Comment by yixinmao** [comment]
I have run and analyzed the Livneh2015 release simulation using the following specification:

- Forcings: Livneh 2015, 3-hourly
- Parameters: Livneh 2015
- Domain: Continental U.S.
- Simulation Dates: Cold start, 1951-1954
- Specs: Full-energy, no frozen-soil

## **ET**
![image](https://cloud.githubusercontent.com/assets/5818020/18217078/a1270eac-710f-11e6-910d-23c20627a77a.png)

## **Total runoff**
![image](https://cloud.githubusercontent.com/assets/5818020/18217087/b9e9bfb6-710f-11e6-8360-d5efbfe43251.png)

## **SWE**
![image](https://cloud.githubusercontent.com/assets/5818020/18217102/d1041868-710f-11e6-877f-4e1655d03b39.png)

## **Soil moistures**
![image](https://cloud.githubusercontent.com/assets/5818020/18217108/d8bb3fa0-710f-11e6-9fd5-1f94a6feaf7b.png)
![image](https://cloud.githubusercontent.com/assets/5818020/18217115/de216a5a-710f-11e6-9181-648c6a31c362.png)
![image](https://cloud.githubusercontent.com/assets/5818020/18217120/e1c779ce-710f-11e6-8cdf-65d069a65886.png)

**Comment by jhamman** [comment]
thanks all.
