### ISSUE TITLE
BUG: Uninitialized variables

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#592]
This is the second part of issue #580, but split into a standalone issue. From #580:

Local variables used before initializing (these do not affect restart, but need to be fixed):

* In `surface_fluxes()`, the local variable `ShortUnderIn` is used before initialized
* In `func_surf_energy_bal()`, line 662-663, variable `fusion` is used; but `fusion` is only initialized if `FROZEN_SOIL=TRUE`

**Comment by bartnijssen** [comment]
@yixinmao : Can you clarify the second issue? Is it actually used before it is uninitialized or is this a compiler warning? The reason I ask is that I am a bit surprised that it would run if the value is never initialized.

Do you know what the values should be initialized to? And can we fix this before 5.0.0 (just the initialization, i.e. item 2).

**Comment by yixinmao** [comment]
@bartnijssen - it seems that all uninitialized variables will be considered as zero if they get used, and compiling and running are both fine (I'm not sure why, but this is what it does). I'll need to look into the physics a bit more to say if initializing the two variables to zero is appropriate.

**Comment by bartnijssen** [comment]
Unfortunately, initialization to zero for an uninitialized variable is compiler-dependent as far as I know and in general is a bad thing to rely on. How did you find this? Was this a compiler warning?

**Comment by yixinmao** [comment]
@bartnijssen `valgrind` threw warnings of uninitialized variables when I was testing for exact restarts. So these two variables here were found "by accident". I don't think there's a compiler warning for these..

**Comment by yixinmao** [comment]
It seems that the two variables are initialized properly before using, and `valgrind` does not raise warnings. The parts of code related to the two variables appear correct and have not been changed since the original issue was open, and not sure why I thought they were not initialized back then...
