### ISSUE TITLE
ENH: Sync netCDF datasets after each write

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#596]
We should call [`nc_sync`](http://www.unidata.ucar.edu/software/netcdf/docs/group__datasets.html#gaf2d184214ce7a55b0a50514749221245) after each call in `vic_write.c` ([line](https://github.com/UW-Hydro/VIC/blob/develop/vic/drivers/shared_image/src/vic_write.c#L221)).

cc @yixinmao, this should help eliminate the crash we were getting last week.

**Comment by bartnijssen** [comment]
Let's make the same run on a different system to make sure whether this was really the problem (rather than an unrelated system crash). If we do end up implementing this, the changes should be made in `vic_mpi_support.c` with an `nc_sync()` following each `nc_put_vara_*()` call.

**Comment by bartnijssen** [comment]
Actually - I think Joe is correct in that the one `nc_sync()` call in `vic_write()` (after writing the time dimenion) should do the trick. If it crashes we should try that first.

**Comment by jhamman** [comment]
closed via #608
