### ISSUE TITLE
ENH: write time bounds variable in netcdf history files

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#615]
As part of this, we should also write the starting cell boundary as the actual time value. Alternatively, we could write the period-middle time stamp? 

cc @bartnijssen and @yixinmao 

xref: http://cfconventions.org/cf-conventions/v1.6.0/cf-conventions.html#cell-boundaries

**Comment by bartnijssen** [comment]
You should provide beginning (always) and possibly bounds (as an extra). Don't confuse by adding mid-steps

**Comment by jhamman** [comment]
closed via #617
