### ISSUE TITLE
Steps toward coupled WRF-VIC simulations using the CESM driver

### ISSUE THREAD

**Issue by jhamman** [UW-Hydro/VIC#633]
With the release of VIC.5, we can now focus getting the CESM driver working properly. Nearly all the pieces are in place, we just need to go through the final debugging and validation steps. This issue will serve as a checklist for those steps:
#### Does the CESM driver compile on the following machines?
- [x] topaz
- [x] spirit
- [x] lightning
- [x] thunder
~- [ ] garnet*~

\* may not be supported
#### RI Case Tests (VIC only)
- [x] Does the model run for multiple years?
- [ ] Does the model stop and restart using flags raised from the coupler?
- [ ] Does the model have exact restarts?
- [x] Does the CESM driver produce the same results as the Image driver?
- [x] Do the coupled fields (fluxes from VIC) in the coupler history files match those in the VIC history files?
- [x] Qualitatively compare the coupler history fields from RASM.1.0.0 with those using VIC.5.
#### RIR Case Tests (VIC + RVIC)
- [ ] Does the model pass the runoff and baseflow fluxes to the coupler appropriately?
#### RFR Case Tests (VIC + RVIC + WRF, prescribed ocean/sea-ice)
- [ ] Complete (~10 year) simulation with WRF version from RASM.1.0.0, compare coupled fields to those from RASM.1.0.0
- [ ] Complete (~10 year) simulation with new WRF version, compare coupled fields to those from RASM.1.0.0 and previous RFR simulation
#### RBR Case Tests (fully-coupled)
- [ ] Complete (~10 year) simulation with WRF version from RASM.1.0.0, compare coupled fields to those from RASM.1.0.0
- [ ] Complete (~10 year) simulation with new WRF version, compare coupled fields to those from RASM.1.0.0 and previous RBR simulation

cc @dgergel, @bartnijssen, @apcraig

**Comment by dgergel** [comment]
@jhamman I don't think it's still useful - I'll go ahead and close it.
