### ISSUE TITLE
Seems `run_cell` not works?

### ISSUE THREAD

**Issue by Sibada** [UW-Hydro/VIC#649]
I had set `run_cell` to 1 at basins in different scale and other gridcells set to 0 but they cost nearly a same time, and each cell output has data. Or it should be set in domain file?

**Comment by bartnijssen** [comment]
Thanks for filing the issue. Please report which version of VIC you are running, what the driver is you are using, etc. As is, it's difficult to do anything with the message.

**Comment by yixinmao** [comment]
@Sibada If you are running VIC5.0.0 image driver, currently the mask variable in the input domain file controls running cells. `run_cell` variable in the image parameter file is not used. Thanks for the issue and we will update the documentation (but as @bartnijssen said, reporting sufficient information inlcuding the version and driver you are using, etc. will help us better handle issues and questions in the future).

**Comment by bartnijssen** [comment]
@yixinmao : Can this be closed or should this remain open?

**Comment by yixinmao** [comment]
@bartnijssen We've decided on a solution, but I haven't implemented changes yet (I looked at it and it needs some work - will do so soon). So maybe keep it open?

**Comment by bartnijssen** [comment]
@yixinmao : Just pinging you to keep this alive and on your radar

**Comment by yixinmao** [comment]
@bartnijssen Thanks Bart! Sorry I've been pushing this back... will work on it soon!

**Comment by Sibada** [comment]
0_0

**Comment by Sibada** [comment]
In fact, I solve this at the next day but I forgot to response here...
I'm using the VIC5 for my research and the paper has nearly been finished, are you have some new papers special for the version 5 could be referenced?

**Comment by jhamman** [comment]
@Sibada - 

We If you have a fix you'd like to share, please open a pull request. @yixinmao can help push that through.

We do have a paper describing the VIC 5 development and model release.  It is also nearing submission.  The citation will be:

> Hamman, J., B. Nijssen, T. Bohn, Y. Mao, and D. Gergel: The Variable Infiltration Capacity (VIC) Model, Version 5.0 - improvements and new applications. In preparation, to be submitted to Geoscientific Model Development - 2017.

**Comment by yixinmao** [comment]
@bartnijssen : I discussed with @jhamman and @dgergel

**Comment by yixinmao** [comment]
@bartnijssen : I discussed with @jhamman and @dgergel , and thought it'd be the most reasonable to consider `mask` variable in the domain file as the biggest possible domain, and `run_cell` variable in the parameter as a switch to turn on/off actual cells to run. Specifically: 1) in the code, check whether all `run_cell = 1` all appears within the `mask` domain; if not, raise an error; 2) after the check, only run cells where `run_cell = 1`. Let me know if you think this is a reasonable way to handle it. I'll take a look at @Sibada 's change as well if he sends along.

**Comment by yixinmao** [comment]
Closed through PR #662

**Comment by yixinmao** [comment]
Closed through PR #662
