### ISSUE TITLE
Numerical issue on soil moisture drainage between layers

### ISSUE THREAD

**Issue by yixinmao** [UW-Hydro/VIC#655]
Drainage from upper layer to adjacent lower layer is calculated by Brook & Corey curve (where drainage rate is a function of upper-layer soil moisture). Currently, a simple numerical solution is applied which uses the timestep-beginning upper-layer soil moisture to calculate drainage rate, and assume this constant rate over the entire timestep. This can cause unreasonably large drainage if the curve has a steep shape and when soil moisture is high.

**Comment by bartnijssen** [comment]
Closed per #656
