### ISSUE TITLE
Seems the Image driver could not run more than 14 years.

### ISSUE THREAD

**Issue by Sibada** [UW-Hydro/VIC#658]
I used the Image driver to run in 1959-1980 and meet segment fault. I have try both the 5.0.0 version of the master branch and the 5.0.1 unreleased version of the develop branch.

I found that it was stop at the line 44 of `get_nc_field.c`: `    status = nc_open(nc_name, NC_NOWRITE, &nc_id);`.
And at that time it was reading the variable `dswrf` from the file `forcing.1973.nc`.

I have tried to run in 1959-1972 and it worked. And when I ran from 1960, 1961, 1962... it stop at reading the forcing file of 1974, 1975, 1976... respectively. This shows that it could read up to 14 forcing files.

What might cause this problem? May be something wrong in my netcdf libraries?

**Comment by Sibada** [comment]
It solved. It really is the problem of the netcdf library. I download the latest netcdf library src file (4.4.1.1) and compiled it manually and recompiled VIC image driver. It normally works.

**Comment by bartnijssen** [comment]
Thanks @Sibada for clarifying and testing this on your end
