### ISSUE TITLE
VIC 5.0 classic driver stops writing to daily output files after 31 years

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#663]
Running 5.0, classic mode, hourly time step, daily output step (ndays=1).  The simulation runs to completion (51 years) but the output files end after 31 years (actually, year 31, month 9, day 16, i.e. Sep 15 of the 31st year).

The reason for this appears to be due to a rounding error in the calculation of the hour and dayseconds of the time step.  At the beginning of the simulation, the dayseconds of the first (hourly) step is 0, and the dayseconds of the final (hourly) step is 82800 (=23 hours * 3600 sec/hour).  After about 14 years (year 14, month 9, day 15 of the simulation, with the first year being year 1), the dayseconds of the final step shifts to 86400, and the dayseconds of the first step of the next day shifts to 3600.  This doesn't stop the writing of output though.  Eventually, output files stop being appended to on year 31, month 9, day 16.  This seems to correspond to the dayseconds beginning to look like 82799 instead of 82800, and so on.

I think this is causing the alarm that tells VIC to write its output on the final step of the day to fail.

This is actually creating 2 problems.  First, the alarm is set for dayseconds=82800.  When the first shift occurs, 82800 becomes the dayseconds of hour 22 instead of hour 23, which means that the daily outputs are being written an hour early.  Then, when the dayseconds of hour 22 becomes 82799, the alarm is no longer raised.  So this means that the output files are really only correct for the first 14 years (approximately).

**Comment by bartnijssen** [comment]
This is a critical bug that needs to be resolved before we make the 5.0.1 release since it prevents long runs in classic mode. Anyone willing to take this on?

**Comment by yixinmao** [comment]
@bartnijssen I can do it. Will coordinate with Ted for some sample data.

**Comment by tbohn** [comment]
A little more information on the bug: changing the origin time to 1800-01-01 in vic_time.c didn't help.  However, changing from NDAYS 1 to NSTEPS 24 fixed the problem in terms of getting the output records written for the entire simulation at the correct time of day, except that the values of dayseconds still were miscalculated - and these incorrect values still appeared in the output file record timestamps.

**Comment by bartnijssen** [comment]
Closed per #668
