### ISSUE TITLE
errno: NetCDF: Variable not found: Error getting variable id for - in /home/arunima/vic/iofiles/forcings/Stehekin_image_test.forcings_10days.1949.nc 

### ISSUE THREAD

**Issue by arunima07** [UW-Hydro/VIC#665]
I am trying to run image driver vic model on sample input files. But I am getting following error - 

[ERROR] ../shared_image/src/get_nc_field.c:50: errno: NetCDF: Variable not found: Error getting variable id for - in /home/arunima/vic/iofiles/forcings/Stehekin_image_test.forcings_10days.1949.nc 

PFA log file generated during run.
[(putvic.log.20170116-30294.000000.txt](https://github.com/UW-Hydro/VIC/files/707635/putvic.log.20170116-30294.000000.txt)

PFA global_parameter_txt file : 
[global_parameter_file.txt](https://github.com/UW-Hydro/VIC/files/707637/global_parameter_file.txt)

**Comment by jhamman** [comment]
I answered your question on the VIC users list but I'll post it here as well.

This error is telling you that VIC cannot find the variable "-". Looking at your global parameter file, you will see a number of erroneous dashes in the variable specification:

```
FORCE_TYPE    AIR_TEMP -   tas    # Average air temperature, K
FORCE_TYPE    PREC -       prcp   # Total precipitation (rain and snow), kg/m2/s
FORCE_TYPE    PRESSURE -   pres   # Atmospheric pressure, Pa
FORCE_TYPE    SWDOWN       dswrf  # Incoming shortwave, W/m2
FORCE_TYPE    LWDOWN ---     dlwrf  # Incoming longwave radiation, W/m2
```

You should remove those.
