### ISSUE TITLE
TESTING: Large-domain release tests: 5.0.1

### ISSUE THREAD

**Issue by yixinmao** [UW-Hydro/VIC#672]
Release tests for VIC5.0.1. The purpose of release tests is to demonstrate the capability of the VIC release version to run successfully on multiple sets of large domain.

We should run the same release tests as 5.0.0 release, including:
- Livneh 2015, CONUS, 1/16 deg - I have run it
- Global 0.5 deg - @dgergel is going to run it
- RASM (image driver) - @dgergel is going to run it

**Comment by yixinmao** [comment]
I have run and summarized the Livneh2015 release run using the following specification:
- Forcings: Livneh 2015, 3-hourly
- Parameters: Livneh 2015
- Domain: Continental U.S.
- Simulation Dates: Cold start, 1951-1954
- Specs: Full-energy, no frozen-soil

**ET**
![evap 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226257/9f887d98-e17a-11e6-8ced-a4a615025257.png)

**Total runoff**
![total_runoff 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226268/b545db9e-e17a-11e6-8e08-fd1fdab54ac6.png)

**SWE**
![swe_apr 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226276/c0c6f296-e17a-11e6-9645-0b8d44b36406.png)

**Soil moistures**
![sm1 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226635/1935a3a4-e17c-11e6-91e1-401570b9c862.png)
![sm2 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226640/1b679736-e17c-11e6-9e6d-637788582581.png)
![sm3 1951_1954](https://cloud.githubusercontent.com/assets/5818020/22226641/1cb83d7a-e17c-11e6-96e3-05130cae6267.png)

**Comment by dgergel** [comment]
I have run and summarized the Global 0.5 degree run with the following specifications: 

- Forcings: CRUNCEP 6-hourly

- Domain: Global

- Simulation Dates: Jan 1, 2006 - Dec 31, 2009

- Specs: Full Energy, no Frozen Soils

- Cluster: Hyak

- Nodes: 2

- Processors: 16/node, 32 total

Seasonal Albedo 
![out_albedo](https://cloud.githubusercontent.com/assets/5017308/22314555/0d421874-e317-11e6-9180-17887755529c.png)

Evaporation
![out_evap](https://cloud.githubusercontent.com/assets/5017308/22314565/19a1ef04-e317-11e6-8a44-7c6dd0b2014e.png)

SWE 
![out_swe](https://cloud.githubusercontent.com/assets/5017308/22314569/22b32a22-e317-11e6-8db1-4868423afc2c.png)

Runoff (Runoff + Baseflow) 
![out_runoff](https://cloud.githubusercontent.com/assets/5017308/22314573/2d59dfb6-e317-11e6-833b-c085bf52a4c0.png)

Soil Moisture (1st layer)
![out_soil_moist](https://cloud.githubusercontent.com/assets/5017308/22314578/3a1aa5be-e317-11e6-9551-ecb1c49d6b7d.png)

**Comment by dgergel** [comment]
I have run and summarized the global domain release run using the following specifications:

Forcings: CRUNCEP, 6-hourly
Domain: Global
Simulation Dates: Cold start, 2006-2009
Specs: Full Energy, no Frozen Soils

SWE
![out_swe](https://cloud.githubusercontent.com/assets/5017308/22494243/c96fbea2-e7ea-11e6-8d0b-ca809ff4fb66.png)

Albedo
![out_albedo](https://cloud.githubusercontent.com/assets/5017308/22494245/cfe60bd8-e7ea-11e6-9275-68eea18f129a.png)

ET
![out_evap](https://cloud.githubusercontent.com/assets/5017308/22494248/d652ffe4-e7ea-11e6-9365-a0905f1e3aa6.png)

Runoff (runoff + baseflow)
![out_runoff](https://cloud.githubusercontent.com/assets/5017308/22494253/dd00c470-e7ea-11e6-865b-b398fd83fbb0.png)

Soil Moisture (1st layer)
![out_soil_moist](https://cloud.githubusercontent.com/assets/5017308/22494257/e24f784a-e7ea-11e6-8e76-227425d2bf6f.png)

**Comment by jhamman** [comment]
Great. Thanks @yixinmao and @dgergel
