### ISSUE TITLE
Fix to typo in image driver vic_force.c

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#673]
VIC 5.0.0 image driver - OS, compiler, settings, etc., are unimportant

In vic_force.c, for the "fcan" variable, the code expects the forcing file to name this variable "fcov".  This needs to be changed to "fcan" to match VIC's name for the variable.

(In fact, the reason this instance of "fcov" exists is due to an incomplete conversion of the variable name from "fcov" to "fcan" throughout the code, which I was responsible for - this is simply a mistake.)

The fix for this should be extremely minor and will have no effects on existing tests or performance since this feature is not yet commonly used.

**Comment by jhamman** [comment]
close via #742
