### ISSUE TITLE
Inconsistency in dimension order for time-varying veg parameters between vic_force.c and vic_init.c

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#674]
In VIC 5.0.0, drivers/image/src/vic_force.c expects time-varying veg parameters such as LAI to have dimensions of (time, veg_class, lat, lon).  But in drivers/shared_image/src/vic_init.c expects LAI to have dimensions of (veg_class, time, lat, lon).

I suggest that we change the dimension order for LAI, fcanopy, albedo, etc. in drivers/image/src/vic_force.c to be consistent with drivers/shared_image/src/vic_init.c.

I believe that this will not have a big impact on users because input of time series of LAI, fcanopy, and albedo via vic_force.c is likely not yet widespread.  (I suspect it has not been used at all yet).

**Comment by yixinmao** [comment]
Thanks @tbohn ! @bartnijssen and @jhamman - since we have already been running release tests for VIC5.0.1 and hope to release this week, I guess we should push this issue and also #673 to the next release?

**Comment by tbohn** [comment]
BTW I'm happy to have this assigned to me.

**Comment by bartnijssen** [comment]
@yixinmao : Yes push it to the next release. I'll create a new milestone and add it to that one.

**Comment by bartnijssen** [comment]
@tbohn : Let me think about this a bit, I wonder whether there was a reason to do it this way. Perhaps it made a different in case only a subset of the veg types have time varying LAI?

**Comment by tbohn** [comment]
I don't know for sure why, either.  A case like that seems unlikely to me, for two reasons: 1. whichever process or data set gives us a time series of LAI for at least some veg classes would probably give it to us for any of the others that exist in the grid cell (if the timeseries doesn't exist for a given veg class, it's presumably because that veg class isn't present in the grid cell under the land cover map that was used); 2. generally the seasonal cycles of LAI are derived via climatological averaging of timeseries (e.g., AVHRR- or MODIS- derived seasonal cycles).

But I suppose a mix of the two types of data could arise if you are using data from multiple land cover maps, and the MODIS (or similar) product was only aggregated over the land cover classes of one of the maps...  Seems like such a case should be prohibited though.

**Comment by tbohn** [comment]
@bartnijssen any more thoughts on this issue?  I've been working on preparing veg history (and climatology) inputs over North America, and I'm nearing the point where I'll need to put them in "final" form for input to VIC.

**Comment by jhamman** [comment]
@bartnijssen can respond but here are my thoughts. I don't think anyone has used the time-varying veg parameters with the image driver to date so if we need to make a braking change, 5.1 (now) is the time to do it. So, in short, we can probably change the code in `vic_init.c` to make things consistent if that is possible.

**Comment by tbohn** [comment]
OK, great.  I'm actually preparing to make this change in the next week or so.  What's the timeline for 5.1?

**Comment by tbohn** [comment]
Just an update: as I prepare the veg_hist parameters for north america, I'm finding that indexing by (veg_class, time, lat, lon) doesn't work nicely in ncview - ncview assigns the "movie" controls (e.g., "play", "fast forward", etc) to the veg_class dimension.

Perhaps that's a good argument for keeping the indexing in vic_force.c as it is and swapping the indices in my veg_hist files...

**Comment by tbohn** [comment]
I propose that we close this issue.  I no longer think it is important.
