### ISSUE TITLE
Implement netcdf speedup in cesm driver

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#686]
See #684. We now have a failing build, because the netcdf speedup has not been implemented in the image driver. This breaks tests.

**Comment by bartnijssen** [comment]
@dgergel  - when you close the issue you need to provide a reference to the PR that closed it. Otherwise this is just a dead end.

For example - closed by PR #692

**Comment by dgergel** [comment]
@bartnijssen yes I should have, my apologies. Will do so in the future.
