### ISSUE TITLE
Mismatched description for units of forcing data in the VIC global parameter file (image mode)

### ISSUE THREAD

**Issue by YifanCheng** [UW-Hydro/VIC#706]
#### Mismatched units description in the global parameter file

- Problem description: In the example for image mode, the unit description for forcing data in global parameter file is different from what it should be
- Example: 
  - the unit for air temperature should be 'C', but it is 'K' in the global parameter file
  - the unit for precipitation should be 'mm', but it is 'kg/m2/s' in the global parameter file

**Comment by jhamman** [comment]
@yixinmao - can you update this https://github.com/UW-Hydro/VIC_sample_data/blob/1554cb017c71e59e114b853af5808649f80ad836/image/Stehekin/parameters/Stehekin_image_test.global.txt#L47-L59

**Comment by jjgudugu** [comment]
I was wondering how to prepare the vegetation timeseries forcings as file forcing2. How many data should I prepare.

**Comment by tbohn** [comment]
These vegetation forcings are optional.  You do not need to generate them.
