### ISSUE TITLE
refactor cesm_put_data routine in CESM driver

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#709]
Currently, the `cesm_put_data.c` routine in the CESM driver writes VIC output to the coupler fields for use by the coupler in RASM. However, this routine repeats many of the calculations that are already in `put_data.c` in `shared_all` in VIC, and thus this introduces potential bugs by allowing for writing different values to the history files and coupler fields. This needs to be updated to use the `out_data` array in `put_data`.

**Comment by jhamman** [comment]
closed via #710
