### ISSUE TITLE
Installation : I am trying to install VIC model using Cygwin. I have put the unzipped VIV model in C:/Cygwin/home/user directory. Changed the directory to vic/drivers/classic. While running make command I am geting the error "fatal: Not a git repository (or any of the parent directories): .git. It would be very kind of you if you would please help me

### ISSUE THREAD

**Issue by ephilip** [UW-Hydro/VIC#717]
#### Bug Reports

- Version of VIC that you are using (e.g. VIC.5.0.0)
- Name and version of the C compiler you are using
- Operating system
- A description of relevant model settings
- A summary of the bug or error message you are getting

#### Feature Requests

- Description of feature
- Description of the problem the feature addresses
- Will the proposed feature be backward compatible?
- Will the proposed feature change the science results of VIC?

**Comment by bartnijssen** [comment]
This github repo is not mean to provide individual support for VIC installations, but to manage source code. As it says in the readme file:

```
While we would like to hear about your particular application (especially a copy of any published paper), we cannot give you individual support in setting up and running the model. The VIC documentation website includes reasonably complete instructions on how to run the model, as well as the opportunity to sign up for the VIC Users Email List. The VIC listserve should be used for questions about model setup and application. It is basically VIC users helping other VIC users. All other exchanges about VIC source code are managed through the VIC github page.
```
