### ISSUE TITLE
How to generate vegetation timeseries files(classical model)?

### ISSUE THREAD

**Issue by jjgudugu** [UW-Hydro/VIC#719]
#### Bug Reports

- VIC.5.0.1
- gcc 4.8.5
- centOS 7
- With only forcing1(meteorological data) I can get the results(soil moisture). Then I prepared Lai, Albedo, and Fcanopy data as forcing2 in the same format with forcing1, but the program didn't work. I was wondering what is the required format for vegetaion timeseries.
- I got the error 'Not enough records in forcing file 2 (1527 * 21600= 32983200) to run the number of records defined in the global file (3052 * 21600 = 65923200)'

#### Feature Requests

- I prepared forcing2 as a file contains vegetaion timeseries of each grid, named in the rule of 'Data_xx.xxx_xx.xxx'. Each grid's forcing file have 3052 lines(time steps) and 3 columns(Lai, Albedo, Fcanopy). I just can't get my results.

**Comment by tbohn** [comment]
@jjgudugu you must have a separate column of LAI, Fcanopy, albedo _**for each vegetation tile within the grid cell**_.  So you would need 3 * nVeg columns:
LAI1 LAI2 ... LAInVeg Fcanopy1 Fcanopy2 ... FcanopynVeg albedo1 albedo2 ... albedonVeg

**Comment by tbohn** [comment]
@jjgudugu did my answer solve your problem?

**Comment by jjgudugu** [comment]
@tbohn Yes！The problem is solved. But I met a new problem 'Segmentation fault (core dumped)', so I gave up using focing2 files. Sorry to reply so late. Thanks for your help.

**Comment by tbohn** [comment]
OK, @jhamman I suggest we mark this issue as resolved and close it...

**Comment by Sqi5986** [comment]
> @tbohn Yes！The problem is solved. But I met a new problem 'Segmentation fault (core dumped)', so I gave up using focing2 files. Sorry to reply so late. Thanks for your help.

hello，how did you solve the problem'Segmentation fault (core dumped)'?Thanks.
