### ISSUE TITLE
fix units and sign for evap passed to coupler CESM driver

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#727]
Currently we are converting `evap` to m by multiplying by `MM_PER_M`, which is not necessary to convert mm to kg m2/s, before we pass it to the coupler in the CESM driver. We're also multiplying by a negative sign. Neither of these are necessary - we just need to divide by `global_param.dt`.

**Comment by bartnijssen** [comment]
Closed per #726
