### ISSUE TITLE
how to install the 5.0.0 version?

### ISSUE THREAD

**Issue by ching12** [UW-Hydro/VIC#728]
I have a problem when installing the 5.0.0 version. I downloaded all the files, and used all the code in vic/drivers/classic/ as the source code, but could not progress. Are they the correct folder and files? Thanks.

**Comment by jhamman** [comment]
@ching12 - please see the [documentation](http://vic.readthedocs.io/en/master/Documentation/Drivers/Classic/RunVIC/) on how to build/configure/run VIC. If you have further questions, please direct them to the vic users [listserve](https://mailman13.u.washington.edu/mailman/listinfo/vic_users)
