### ISSUE TITLE
problem in specifying snow model timestep

### ISSUE THREAD

**Issue by shahryaramd** [UW-Hydro/VIC#757]
#### Bug Reports

- VIC version 5.0.1 - Classic driver
- Name and version of the C compiler: gcc version 5.4.0
- Linux (Ubuntu 16.04)
- A description of relevant model settings: See attached global parameter file: [global.param.mekong5.0.1.txt](https://github.com/UW-Hydro/VIC/files/1450818/global.param.mekong5.0.1.txt)
- Summary of error: While setting up VIC v5.0.1 for my project, I am facing a problem in specifying parameters in the global parameter file. I need to run the VIC at daily time step (at which I have prepared my forcing data). Now, I get an error saying " minimum number of subdaily steps per day = 4" when I give the following options:
MODEL_STEPS_PER_DAY 	1	
SNOW_STEPS_PER_DAY	1	
RUNOFF_STEPS_PER_DAY	1
...
FORCE_STEPS_PER_DAY	1

 So when I set SNOW_STEPS_PER_DAY = 4, I then get an error saying "FORCE_STEPS_PER_DAY must match SNOW_STEPS_PER_DAY". However, I have prepared my forcing files at daily time step.
How can I make the VIC model run at daily time step?

**Comment by arbennett** [comment]
Hey @shahryaramd I don't think that VIC can be run at a daily time step.  One way to accomplish what you're trying to do would be to use [MetSim](https://github.com/UW-Hydro/MetSim) to disaggregate your data to sub-daily values and then feed those through VIC.  If you need any help getting MetSim up and running open an issue on it's repo and I'll help you out.

**Comment by shahryaramd** [comment]
Thanks @arbennett, has this change occurred starting VIC v5, because v4.x allowed running at the daily step?
I will try setting up MetSim and open an issue if in case of any problem.

**Comment by arbennett** [comment]
Yes, this was a change with VIC 5 (I went back and edited my comment to make things clearer for others).

**Comment by shahryaramd** [comment]
Thanks for the clarification.

**Comment by tbohn** [comment]
@shahryaramd you are likely to encounter problems with MetSim.  The latest version on the develop branch doesn't output all the variables that VIC will need - in particular it is missing wind and pressure.  In addition, it only runs on one input file at a time.  Unless you have an input file containing the entire time series that you need, all in one file, you will have to run MetSim manually or write a script to loop over all the input files and concatenate the results.

Kristen Whitney has been developing solutions to both of these problems.  Her code is basically usable at this point, although we are still putting the finishing touches on it.  Take a look at @kwhitney727's feature/time_wrap branch of MetSim.

**Comment by tbohn** [comment]
Note that this isn't to disparage @arbennett's work in creating MetSim (it's a great product!).  Just pointing out a practical problem (for which a solution is nearly complete).

**Comment by shahryaramd** [comment]
thanks for letting me know, will try that out.

**Comment by arbennett** [comment]
@tbohn @shahryaramd this isn't really the place to discuss MetSim, but I don't want to spread misinformation.  MetSim **can** output wind and pressure.  All of this information can be found in the [documentation](http://metsim.readthedocs.io/en/develop/index.html).

**Comment by tbohn** [comment]
Sorry @arbennett - perhaps I misunderstood.

**Comment by jhamman** [comment]
Okay, it sounds like we've moved on from the original issue. I'm going to close this now and further discussion can be had over on the MetSim Github Issues. 

@shahryaramd - VIC 5 removed the METSIM disaggregattor (#288) so you need to generate these subdaily forcings as a preprocessing step. It's worth noting that VIC always ran at a subdaily time, users just had the option of letting VIC do the disaggregation on the fly with METSIM. Your misunderstanding of VIC's capabilities is exactly why we removed the tool from VIC.
