### ISSUE TITLE
Comparing two versions of VIC model.

### ISSUE THREAD

**Issue by Hadiheidari17** [UW-Hydro/VIC#758]
Hello,

I am going to compare the results of  VIC 4.2 to VIC 5.1 for my study area. However, as far as I understand, we cannot use the same forcing files for both of them. Is there any way to run the VIC 5.1 with the same PreP, Tmin, Tmax and Wind data. In not, it is logical to compare the outputs of VIC model with different forcing files. That is because the required inputs in new version are AIR_TEMP (average temperature), PREC, PRESSURE, SWDOWN, LWDOWN (Incoming shortwave and longwave radiation, Vapor pressure and Wind Speed. 

Thank you,
Hadi

**Comment by jhamman** [comment]
@Hadiheidari17. I think this question is better directed to the VIC users list serve: vic_users@u.washington.edu. If you wouldn't mind posting your question there, someone will answer it in proper detail.
