### ISSUE TITLE
VIC v5.0.1 producing -nan values at 120 min timestep

### ISSUE THREAD

**Issue by shahryaramd** [UW-Hydro/VIC#761]
#### Bug Reports

- Version of VIC - VIC 5.0.1
- Name and version of the C compiler you are using - gcc 5.4.0
- Operating system - Ubuntu 16.04
- A description of relevant model settings - _attached below_

As the VIC only runs at sub-daily forcings, I used MetSim to disaggregate the daily forcings to 2-hourly. Now, when  I am trying to run VIC at 120min timestep, the VIC output files have -_nan_ values for the columns of OUT_EVAP, OUT_RUNOFF and for the 1st soil layer values of OUT_SOIL_LIQ and OUT_SOIL_MOIST. I can't figure out why. I have attached the global param file, a sample forcing file, and corresponding output file.

[global.param.mekong.txt](https://github.com/UW-Hydro/VIC/files/1549770/global.param.mekong.txt)
[forcing_9.6_105.4.txt](https://github.com/UW-Hydro/VIC/files/1549771/forcing_9.6_105.4.txt)
[fluxes_9.6_105.4.txt](https://github.com/UW-Hydro/VIC/files/1549772/fluxes_9.6_105.4.txt)

**Comment by jhamman** [comment]
@shahryaramd - 

When you say that you can't figure out why, what have you tried?  Have you tried using a debugger to isolate when the nans are created?

**Comment by jhamman** [comment]
@shahryaramd - Closing as we never heard back from you. Feel free to reopen if you are able to provide more information.

**Comment by shahryaramd** [comment]
I actually was able to solve the problem. On changing the SOIL_QUARTZ value from -999 to a finite value solved it.
