### ISSUE TITLE
VIC AUTOMATIC CALIBRATION

### ISSUE THREAD

**Issue by trishani** [UW-Hydro/VIC#762]
I had been using VIC 4.2.d for simulating the water balance fluxes for one of the Indian catchment and also routed the fluxes to get the discharge.I have also downloaded the source code for automatic calibration(Calibrate_other).But I am not able to run the code in Linux.Do I need to include the VIC source code in the calibration source code folder?Is the source code given for calibration in the website can be considered for automatic calibration? I would request you to help me in the calibration part or give some ideas about how to proceed with the calibration.
- Version of VIC VIC.4.2.d
- Name and version of the C compiler you are using-GCC
- Operating system Linux
- A description of relevant model settings
- A summary of the bug or error message you are getting

#### Feature Requests

- Description of feature
- Description of the problem the feature addresses
- Will the proposed feature be backward compatible?
- Will the proposed feature change the science results of VIC?

**Comment by jhamman** [comment]
@trishani - 

Please email the VIC users list: vic_users@u.washington.edu

You're more likely to get help with how to use VIC there.
