### ISSUE TITLE
Cleanup: Change forcing variable LAI_IN to LAI

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#763]
- Version VIC.5.0.1
- This is just a very minor change: changing the name of the forcing variable `LAI_IN` to `LAI`.  This is just for simplicity/aesthetics.  I think it used to conflict with another instance of the term `LAI` but no longer does.
- This is technically not backwards-compatible as it requires users to update their global parameter files to list `LAI` instead of `LAI_IN` as a historical forcing variable.  However, I believe I might be the only user to have used this feature so far, and I am happy to make this change.

**Comment by jhamman** [comment]
Yes, this belongs in 5.1. Can you put this together in association with #764?

**Comment by tbohn** [comment]
Yep, this is already in my PR #723

**Comment by tbohn** [comment]
Closed by PR #723
