### ISSUE TITLE
Cleanup: Change netcdf names for vegetation forcing variables fcanopy and albedo

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#764]
- Version 5.0.1 develop
- Changing the names of vegetation forcing variables from `fcan` and `alb` to `fcanopy` and `albedo`, for consistency with their names in the params file.
- Technically not backwards-compatible, but as I believe I'm the only user of this feature so far, I don't anticipate problems.

**Comment by jhamman** [comment]
@tbohn - I think 5.1 is the right place for this. Can you put this together in the next few days?

**Comment by tbohn** [comment]
Yep, it's already in my PR #723

**Comment by tbohn** [comment]
Closed by PR #723
