### ISSUE TITLE
move MAX_ITER_GRND_CANOPY to parameters struct

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#770]
Currently, to modify the number of nested ground-canopy iterations in the `surface_fluxes.c` routine in `vic_run`, `MAX_ITER_GRND_CANOPY` has to be altered within the `surface_fluxes.c` routine. It could be moved to the parameters struct so that it can be altered more easily in the event of wanting to reduce the number of maximum iterations before falling back.

**Comment by jhamman** [comment]
closed via #771
