### ISSUE TITLE
Automatic Calibration

### ISSUE THREAD

**Issue by Riaz3672** [UW-Hydro/VIC#782]
Hi
I am trying the automatic calibration procedure. I want help for automatic calibration
#### Bug Reports

- Version of VIC that you are using (e.g. VIC.5.0.0)
- Name and version of the C compiler you are using
- Operating system
- A description of relevant model settings
- A summary of the bug or error message you are getting

#### Feature Requests

- Description of feature
- Description of the problem the feature addresses
- Will the proposed feature be backward compatible?
- Will the proposed feature change the science results of VIC?

**Comment by jhamman** [comment]
@Riaz3672 - this is a usage question and the best place for it is the VIC users list serve: vic_users@u.washington.edu
