### ISSUE TITLE
Documentation needs to list the version of uncrustify that is required for development

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#783]
- VIC Version: 5.0
- Compiler: gcc 5.4.0
- OS: ubuntu 
- Problem: running uncrustify is a required step when developers submit PRs.  However, running the wrong version of uncrustify will result in undesirable code changes.  On Ubuntu at least, the latest version of uncrustify currently available for a simple installation (v 0.59) is too old, and gives bad results.  Upgrading to 0.64 or later fixes the problem (we don't know the exact version that fixes the problem; all we know is that 0.64 is new enough).  This required extra effort on my part to explicitly download the source code for a newer version of uncrustify and build it.
- Proposed solution: we should add a clear statement to the online documentation that uncrustify 0.64 or later is required, if one wants to submit a PR (and fulfill the uncrustify requirement of the PR).  It's only necessary for developers, so I guess the statement should go somewhere in the development section.
- Note also that running uncrustify within the vic_test_env environment MIGHT also be necessary.  Haven't tested that for sure.  I'll try to find out and update this.

**Comment by jhamman** [comment]
@tbohn - uncrustify is not exactly a "required dependency". While it is for developers, it is not for most users so I'm hesitant to elevate its place in the dependency list.  That said, I think we should add a few notes about the traditional development environment to this page: http://vic.readthedocs.io/en/master/Development/Contributing/

**Comment by dgergel** [comment]
I can take care of this when I get back (I'm out tomorrow and this weekend)

**Comment by tbohn** [comment]
OK, I've changed the title of the issue to not mention required dependency.  But the version of uncrustify still needs to be specified.

**Comment by dgergel** [comment]
Closed via #796
