### ISSUE TITLE
parameters documentation definitions missing some necessary VIC 5 parameters

### ISSUE THREAD

**Issue by dgergel** [UW-Hydro/VIC#784]
Our current documentation of VIC 5 parameters is missing definitions for a bunch of the parameters, descriptions of the missing ones (for example, quartz content) need to be added to this page: https://vic.readthedocs.io/en/develop/Documentation/Definitions/

**Comment by jhamman** [comment]
@dgergel - can you take this on?

**Comment by dgergel** [comment]
@jhamman sure - I'll take care of it sometime in the next week.

**Comment by dgergel** [comment]
Closed via #791
