### ISSUE TITLE
Test data sets

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#79]
We need to develop a test data sets that can be used to ensure that changes to VIC do what they are supposed to do and do not have any unintended side consequences. I will open a series of issues for this, since we'll need different test datasets for different use cases. This issue will serve as the parent issue that can be closed when all the test data sets have been developed. Note that these test cases may need to be updated as we update VIC.

Eventual goal: Something that would allow us to run a series of automated tests after source code changes have been made to VIC (somewhat analogous to travis for compilation).

Note that:
- Simplifying the number of options that are used within VIC will facilitate this testing configuration.
- Small tests that test specific behaviors would be ideal (so they can help in isolating problems).

Test cases:
- no change in output format or calculated values:
  - Comparison with prior VIC output
- change in output format but no change in calculated values:
  - Comparison with prior VIC output
- no change in output format but change in calculated values:
  - Comparison with prior VIC output
  - Comparison with observations

**Comment by jhamman** [comment]
I'm getting close to being done with this work for this issue. How do we feel about putting these datasets in new github repo (https://github.com/UW-Hydro/VIC_test_data)? Total size of the datasets is about 1GB and I'd like to use [git-lfs](https://git-lfs.github.com/) to store the data on github.

I currently have four datasets formatted into netCDF4 ready for the test module: 
- Stehekin sample dataset
- Snotel (from Chiyu Lin)
- Ameriflux towers
- Rosemount sample dataset

**Comment by tbohn** [comment]
Sounds good to me.

**Comment by bartnijssen** [comment]
Same here - `git-lfs` may also be a good place for the SUMMA test data. I wasn't aware that they already started this (I know it was in the works)

**Comment by jhamman** [comment]
partially completed by #387 

follow up PRs will add science and release test datasets.

**Comment by jhamman** [comment]
@dgergel's science testing PR has just been merged (#544).  With that done, we just have to put all the test datasets together in one place. I'll work with @dgergel to pull this together.  For now, let's just create a directory on our groups FTP.  We'll want to put the science and release data in there so we can all start using it.
