### ISSUE TITLE
[Bug] Garbage when run_cell is not identical to mask

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#798]
- VIC 5.1.0.rc1
- gcc
- Ubuntu
- Image driver
- Problem description:
-- When I set the `run_cell` variable in my parameter file to skip some of the cells in the domain (which still have `mask == 1`) VIC's indexing of the cells gets confused and I encounter a lot of Nans.
- Proposed solution:
-- Need to modify `vic_init.c` and `vic_force.c`, when reading multi-dimensional slices from netcdf files, to loop over `ncells_total` instead of `ncells_active`, and insert a check on the value of `locations[i].run` when assigning variables from these files to internal 1-d arrays.

**Comment by jhamman** [comment]
@dgergel - haven't you used this functionality? Have you seen similar behavior?

**Comment by dgergel** [comment]
I have used that functionality but I think I've always altered the `run_cell` variable in the parameter file and the `mask` variable in the domain file in tandem, so I haven't seen this behavior. When I have altered `run_cell` and `mask` I have checked that those grid cells have identical behavior to domain-wide runs, and they do. But I have thought that we should be able to alter `run_cell` to do limited gridcell runs without having the `mask` match

**Comment by tbohn** [comment]
I think I can have a fix ready by Friday...

**Comment by tbohn** [comment]
but I understand if you don't want to include it in the release...

**Comment by jhamman** [comment]
Full steam ahead @tbohn! Go ahead and pursue the fix if you can.

**Comment by tbohn** [comment]
Status update: My earlier hypothesis as to the cause of the problem was wrong.  The logic inside `get_scatter_nc_field_*` appears to correctly account for `run_cell` via the `filter_active_cells` array.  This problem MAY be related to the `OMP_NUM_THREADS` issue and my unorthodox library setup (pointing to `anaconda` libraries).

However, although setting `OMP_NUM_THREADS=1` fixed the earlier problem I had when `run_cell` was the same as `mask`, it does not prevent the current problem.

So far, I'm seeing that inside `vic_image_run()`, the cells are being looped over in a weird order (despite the loop being `for (i = 0; i < local_domain.ncells_active; i++) {`, the actual `i` values are not in order, presumably due to OpenMPI?).  It doesn't cause a problem when `run_cell` == `mask`.  But when they're not equal, it MIGHT be possible that different data structures are getting indexed in different orders.  I'm working on pinning this down.  If it turns out to be a clear bug in the logic (independent of my OpenMPI setup) then I'll try to fix it.

It could be possible that @dgergel didn't encounter any problems due to her `run_cell == 1` for only one cell (ie, no possibility for order to be mixed up, since the set of active cells has no order to mix up).

**Comment by tbohn** [comment]
Update: running on a different machine (still pointing to `anaconda` libraries) doesn't encounter the out-of-order cell order problem that I was seeing.  In both cases, `OMP_NUM_THREADS=1`.  So something else was clearly wrong with my first machine.  Tests are running on the new machine to determine whether `run_cell` works correctly.

**Comment by tbohn** [comment]
At this point, as far as I can tell, `run_cell` does work correctly.  I have not yet figured out the causes of the errors that I encountered, but they only occur on certain machines and/or for certain parameter files.  For other parameter files on a different machine, setting `run_cell` to a subset of the mask does work correctly.  So, I think this issue can be closed.
