### ISSUE TITLE
Cleanup of tools directory

### ISSUE THREAD

**Issue by bartnijssen** [UW-Hydro/VIC#80]
I have no idea how useful the actual tools directory is. Does anyone ever use this?

We should clean this out and make sure it actually aligns / is relevant to recent versions of VIC. It's in the github archive, so people can alway retrieve past tools, but if they are not maintained (or only support very specific use cases or old VIC releases) then they should be removed.

**Comment by jhamman** [comment]
How do we want to determine what tools are useful?  I have not used anything in the tools directory but I'm sure some users have.  One option would be to ask the vic_users email list.  Maybe @tbohn knows more about what tools are still useful and which are out of date.

**Comment by tbohn** [comment]
I will take a look in there today and see if I can shed some light on it...

**Comment by bartnijssen** [comment]
I don't really want to delete tools just because we don't use them, on the other hand I don't want to have just a random collection of non-usable tools. One option is to split it into a legacy and active directory, with the first containing the 'random' collection and the other the active set of maintained tools.

If there is a way to point to other repos as well that would be good. For example Joe's VICpy utils.

**Comment by jhamman** [comment]
So this long list is everything in the `VIC/tools/` directory.  Surely, we don't need to keep all these in the repo.  Let's check those we can get rid of:


- [ ] ├── ./basin_delineation
- [ ] │   └── ./basin_delineation/basin_prep
- [ ] │       ├── ./basin_delineation/basin_prep/README.txt
- [ ] │       ├── ./basin_delineation/basin_prep/multiply_basin_param.c
- [ ] │       ├── ./basin_delineation/basin_prep/set_basin_param.c
- [ ] │       └── ./basin_delineation/basin_prep/sum_basin_param.c
- [ ] ├── ./calibration
- [ ] │   └── ./calibration/calibrate_other
- [ ] │       ├── ./calibration/calibrate_other/calibrate_wis_opti.script
- [ ] │       ├── ./calibration/calibrate_other/compute_R2.c
- [ ] │       ├── ./calibration/calibrate_other/make_convolution.f
- [ ] │       ├── ./calibration/calibrate_other/opti.put_data.c
- [ ] │       ├── ./calibration/calibrate_other/opti.write_data.c
- [ ] │       ├── ./calibration/calibrate_other/optimize_vic.c
- [ ] │       ├── ./calibration/calibrate_other/run_opt_wis_calib.script
- [ ] │       ├── ./calibration/calibrate_other/wis_file_list
- [ ] │       ├── ./calibration/calibrate_other/wis_file_list_opti
- [ ] │       ├── ./calibration/calibrate_other/wis_global_ewb_calib_opt
- [ ] │       ├── ./calibration/calibrate_other/wis_global_fs_ewb_calib_opt
- [ ] │       └── ./calibration/calibrate_other/wis_run.asc
- [ ] ├── ./code_format
- [ ] │   ├── ./code_format/readme.md
- [ ] │   ├── ./code_format/run_uncrustify.bash
- [ ] │   └── ./code_format/uncrustify_VIC_c.cfg
- [ ] ├── ./ide
- [ ] │   └── ./ide/xcode_setup.md
- [ ] ├── ./meteorological_data
- [ ] │   ├── ./meteorological_data/GRID_2000
- [ ] │   │   ├── ./meteorological_data/GRID_2000/NCAR-wind
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCAR-wind/gauss_t62_lat.list
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCAR-wind/gauss_t62_lon.list
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCAR-wind/getwind.scr
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCAR-wind/regrid_wind.c
- [ ] │   │   │   └── ./meteorological_data/GRID_2000/NCAR-wind/run_regrid_wind.scr
- [ ] │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents/APPX_GRID.DOC
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents/APPX_GRID.pdf
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents/GRID_2000.DOC
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents/GRID_2000.pdf
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/documents/grid_flow.doc
- [ ] │   │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/documents/grid_flow.pdf
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/filenames
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/get_prism.c
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/mk_monthly.c
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/prec_tob_adj.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/prec_tob_adj.input
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/preproc_precip.scr
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/read_prec_dly.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/read_precip.input
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/rescale.c
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/run.mk_monthly.scr
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/run_get_prism.scr
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/prcp/run_rescale.scr
- [ ] │   │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/prcp/tob
- [ ] │   │   │   │       └── ./meteorological_data/GRID_2000/NCDC-daily/prcp/tob/coop_tob.his
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/Makefile
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/argtest.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/array_dims.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/chgtemp.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/grd.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/indexx.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/isaleap.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/iso_weight.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/latlong.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/near_neigh.f
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid/regrid.runfile
- [ ] │   │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/regrid/symap.f
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/regrid.runfile
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmax
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmax/filenames
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmax/preproc_tmax.scr
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmax/read_temp.input
- [ ] │   │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/tmax/read_temp_dly.f
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmin
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmin/filenames
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmin/preproc_tmin.scr
- [ ] │   │   │   │   ├── ./meteorological_data/GRID_2000/NCDC-daily/tmin/read_temp.input
- [ ] │   │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/tmin/read_temp_dly.f
- [ ] │   │   │   └── ./meteorological_data/GRID_2000/NCDC-daily/vicinput
- [ ] │   │   │       ├── ./meteorological_data/GRID_2000/NCDC-daily/vicinput/check.c
- [ ] │   │   │       ├── ./meteorological_data/GRID_2000/NCDC-daily/vicinput/run_vicinput.scr
- [ ] │   │   │       └── ./meteorological_data/GRID_2000/NCDC-daily/vicinput/vicinput.c
- [ ] │   │   ├── ./meteorological_data/GRID_2000/append_met
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/README.append
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/append_prcp.c
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/append_temp.c
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/filenames
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/preproc_append.scr
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/preproc_append_prcp.AWK
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/preproc_append_tmax.AWK
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/preproc_append_tmin.AWK
- [ ] │   │   │   ├── ./meteorological_data/GRID_2000/append_met/run_append_prcp.scr
- [ ] │   │   │   └── ./meteorological_data/GRID_2000/append_met/run_append_temp.scr
- [ ] │   │   ├── ./meteorological_data/GRID_2000/combine_wind.c
- [ ] │   │   └── ./meteorological_data/GRID_2000/run_combine_wind.scr
- [ ] │   ├── ./meteorological_data/US_LOOKUP_TABLES
- [ ] │   │   ├── ./meteorological_data/US_LOOKUP_TABLES/hly_prcp.inf
- [ ] │   │   ├── ./meteorological_data/US_LOOKUP_TABLES/hp_dur.lookup
- [ ] │   │   └── ./meteorological_data/US_LOOKUP_TABLES/hp_hour.lookup
- [ ] │   ├── ./meteorological_data/met_prep_other
- [ ] │   │   ├── ./meteorological_data/met_prep_other/README.txt
- [ ] │   │   ├── ./meteorological_data/met_prep_other/ascend.c
- [ ] │   │   ├── ./meteorological_data/met_prep_other/format_wind.scr
- [ ] │   │   ├── ./meteorological_data/met_prep_other/get_prism_airtemp.aml
- [ ] │   │   ├── ./meteorological_data/met_prep_other/implement_wind_vic.c
- [ ] │   │   ├── ./meteorological_data/met_prep_other/mk_monthly_airtemp.c
- [ ] │   │   ├── ./meteorological_data/met_prep_other/rescale_airtemp.c
- [ ] │   │   ├── ./meteorological_data/met_prep_other/run_mk_monthly_airtemp.scr
- [ ] │   │   └── ./meteorological_data/met_prep_other/run_rescale_airtemp.scr
- [ ] │   └── ./meteorological_data/temporal_disagg_precip
- [ ] │       ├── ./meteorological_data/temporal_disagg_precip/README.txt
- [ ] │       ├── ./meteorological_data/temporal_disagg_precip/disagg_prec.c
- [ ] │       ├── ./meteorological_data/temporal_disagg_precip/make_lookup_table.c
- [ ] │       ├── ./meteorological_data/temporal_disagg_precip/reformat_prcp.scr
- [ ] │       ├── ./meteorological_data/temporal_disagg_precip/run_disagg_prec.scr
- [ ] │       └── ./meteorological_data/temporal_disagg_precip/run_make_lookup.scr
- [ ] ├── ./parameter_files
- [ ] │   ├── ./parameter_files/LDAS_prep
- [ ] │   │   ├── ./parameter_files/LDAS_prep/LDAS_2_vegparam.c
- [ ] │   │   ├── ./parameter_files/LDAS_prep/README.txt
- [ ] │   │   ├── ./parameter_files/LDAS_prep/extract_daily_means_from_LDAS_binary.c
- [ ] │   │   └── ./parameter_files/LDAS_prep/quick_read_LDAS_format.c
- [ ] │   ├── ./parameter_files/snowband_prep
- [ ] │   │   ├── ./parameter_files/snowband_prep/README.txt
- [ ] │   │   ├── ./parameter_files/snowband_prep/elevband.c
- [ ] │   │   ├── ./parameter_files/snowband_prep/run_snowband.scr
- [ ] │   │   ├── ./parameter_files/snowband_prep/snowband.c
- [ ] │   │   └── ./parameter_files/snowband_prep/snowband.py
- [ ] │   ├── ./parameter_files/soil_param_prep
- [ ] │   │   ├── ./parameter_files/soil_param_prep/README.txt
- [ ] │   │   └── ./parameter_files/soil_param_prep/standard
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/Scalesrf.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/aggr_soil_2vic.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/clipSoilVariable.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/clipSoilVariableClass.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/convert_ARCINFO_to_ASCII_soil_file.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/convert_srf_to_text.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/cosby.1984.csv
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/create_soilf.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/fix_resid.pl
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/get_van_GN.c
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/make_5min_ll_data.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/make_arc30_ll_data.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/make_clipsoil.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/make_my_ll_data.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/make_parametersfiles.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/run_awk_nv.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/run_soil_aggr.scr
- [ ] │   │       ├── ./parameter_files/soil_param_prep/standard/set_moist.pl
- [ ] │   │       └── ./parameter_files/soil_param_prep/standard/texture2prop.awk
- [ ] │   └── ./parameter_files/veg_param_prep
- [ ] │       ├── ./parameter_files/veg_param_prep/LDAS_2_vegparam.c
- [ ] │       ├── ./parameter_files/veg_param_prep/README.txt
- [ ] │       └── ./parameter_files/veg_param_prep/aggregate_LAI_veg_param.c
- [ ] ├── ./plotting_scripts
- [ ] │   ├── ./plotting_scripts/R_plot_scripts.tgz
- [ ] │   └── ./plotting_scripts/plot_flow_STEHE.scr
- [ ] ├── ./post_processing
- [ ] │   ├── ./post_processing/flux2nc.py
- [ ] │   ├── ./post_processing/spatial_agg
- [ ] │   │   ├── ./post_processing/spatial_agg/README.txt
- [ ] │   │   ├── ./post_processing/spatial_agg/aggregate_LAI_veg_param.c
- [ ] │   │   ├── ./post_processing/spatial_agg/aggregate_binary_metdata.c
- [ ] │   │   ├── ./post_processing/spatial_agg/aggregate_metdata.c
- [ ] │   │   ├── ./post_processing/spatial_agg/aggregate_soil_data.c
- [ ] │   │   ├── ./post_processing/spatial_agg/aggregate_veg_param.c
- [ ] │   │   ├── ./post_processing/spatial_agg/latlong.c
- [ ] │   │   ├── ./post_processing/spatial_agg/make_accumulation.c
- [ ] │   │   ├── ./post_processing/spatial_agg/make_new_direction.c
- [ ] │   │   ├── ./post_processing/spatial_agg/make_new_fraction.c
- [ ] │   │   └── ./post_processing/spatial_agg/spatial_agg.tgz
- [ ] │   ├── ./post_processing/spatial_disagg
- [ ] │   │   ├── ./post_processing/spatial_disagg/README.txt
- [ ] │   │   ├── ./post_processing/spatial_disagg/Scalesrf.c
- [ ] │   │   ├── ./post_processing/spatial_disagg/convert_srf_to_text.scr
- [ ] │   │   ├── ./post_processing/spatial_disagg/make_arc30_ll_data.scr
- [ ] │   │   ├── ./post_processing/spatial_disagg/make_my_ll_data.scr
- [ ] │   │   └── ./post_processing/spatial_disagg/run_soil_aggr.scr
- [ ] │   └── ./post_processing/temporal_agg
- [ ] │       ├── ./post_processing/temporal_agg/README.txt
- [ ] │       ├── ./post_processing/temporal_agg/agg_time.pl
- [ ] │       ├── ./post_processing/temporal_agg/extract_daily_means_from_LDAS_binary.c
- [ ] │       └── ./post_processing/temporal_agg/make_file_list.script
- [ ] └── ./state_file_conversion
- [ ]     └── ./state_file_conversion/convert_state_file.pl

The old VIC website also included these scripts as well:
- [ ] [text_wcrit.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/text_wcrit.aml)
- [ ] [text_wcrit.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/text_wiltp.aml)
- [ ] [text_ks.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/text_ks.aml)
- [ ] [s_c_frac.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/s_c_frac.aml)
- [ ] [poros.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/poros.aml)
- [ ] [bulkdens.aml](http://www.hydro.washington.edu/Lettenmaier/Models/VIC/Documentation/Info/bulkdens.aml)

And references to these other packages:
- [ ] [basin_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/basin_prep.tgz)
- [ ] [GRID_2000.TAR.gz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/GRID_2000.TAR.gz)
- [ ] [CANADA_MET.TAR.gz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/CANADA_MET.TAR.gz)
- [ ] [met_prep_other.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/met_prep_other.tgz)
- [ ] [temporal_disagg_precip.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/temporal_disagg_precip.tgz)
- [ ] [US_LOOKUP_TABLES.TAR.gz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/US_LOOKUP_TABLES.TAR.gz)
- [ ] [veg_param_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/veg_param_prep.tgz)
- [ ] [soil_param_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/soil_param_prep.tgz)
- [ ] [soil_param_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/soil_param_prep.tgz)
- [ ] [snowband_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/snowband_prep.tgz)
- [ ] [LDAS_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/LDAS_prep.tgz)
- [ ] [rout_prep.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/rout_prep.tgz)
- [ ] [temporal_agg.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/temporal_agg.tgz)
- [ ] [spatial_agg.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/spatial_agg.tgz)
- [ ] [spatial_disagg.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/spatial_disagg.tgz)
- [ ] [flux2nc.py](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/flux2nc.py)
- [ ] [calibrate_other.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Utility_Programs/calibrate_other.tgz)
- [ ] [R_plot_scripts.tgz](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Plotting_Scripts/R_plot_scripts.tgz)
- [ ] [plot_flow_STEHE.scr](ftp://ftp.hydro.washington.edu/pub/HYDRO/models/VIC/Plotting_Scripts/plot_flow_STEHE.scr)

**Comment by jhamman** [comment]
@bartnijssen - 

@tbohn and I just discussed this and basically came to the conclusion that basically everything here can go.  There are a few exceptions but for the most part, these "tools" are way out of date and will not be particularly useful moving forward.  They will remain in the repo's history if we ever want to come back to them.

This issue will be resolved via two commits:

1. removal of tools
2. changes to docs that reference these tools

**Comment by bartnijssen** [comment]
Agreed

**Comment by bartnijssen** [comment]
Closed per PR #250
