### ISSUE TITLE
Can I use the STEHE sample data for the sample data for my R package of VIC?

### ISSUE THREAD

**Issue by Sibada** [UW-Hydro/VIC#802]
I plan to upload my VIC R package to GitHub and upload it to CRAN in this week. Generally sample data for R package is normally necessary and it would be most convenient to use the STEHE sample data of UW.

**Comment by jhamman** [comment]
@Sibada - Yes, you can use it provided your application complies with the license. The dataset is licensed under the same terms as VIC: https://github.com/UW-Hydro/VIC_sample_data/blob/master/LICENSE
