### ISSUE TITLE
outfile time:year,month,day,sec,is the startyear,startmonth,startday,startsec?

### ISSUE THREAD

**Issue by li984096131** [UW-Hydro/VIC#808]
Version of VIC :5.0.1 Feb1,2017
gcc and g++
linux ubuntu 16.4?

simulation, fluxes

outfile  time:year,month,day,sec,is the startyear,startmonth,startday,startsec in Global Parameter File ?
but the soil moist 0,1,2 is the value of after run vic?

thank you

**Comment by jhamman** [comment]
I'm going to close this. The question included above isn't enough to respond to. If you are having trouble running VIC, I suggest sending an email to the VIC users listserve.
