### ISSUE TITLE
Shall I add you as the "contributer" role to the author list in my R package of VIC?

### ISSUE THREAD

**Issue by Sibada** [UW-Hydro/VIC#811]
According to the policy of CRAN, all the contributers of the codes used by the R package should be in the author list and marked by a "role".

According to http://r-pkgs.had.co.nz/description.html:

> A three letter code specifying the role. There are four important roles:
> cre: the creator or maintainer, the person you should bother if you have problems.
> aut: authors, those who have made significant contributions to the package.
> ctb: contributors, those who have made smaller contributions, like patches.
> cph: copyright holder. This is used if the copyright is held by someone other than the author, typically a company (i.e. the author’s employer).

For example, @jhamman might be presented as (if wrong please correct, thanks):
```R
person("Joe", "Hamman", role = c("ctb"), comment = "Contributer and maintainer of VIC source code")
```
Generally, only the author marked by "cre" (maintainer) should be responsible for the R package, while other roles are set for acknowledgement of their contributions or their copyright statement.

**Comment by jhamman** [comment]
The challenge here is that I (we) didn't contribute directly to the r package. If you feel it is worth mentioning us by name, the citation is certainly appreciated. 

```r
person("Joseph J", "Hamman", role = c("ctb"), comment = "Contributor and maintainer of VIC source code")
```

also ping @tbohn @bartnijssen @dgergel @yixinmao

**Comment by Sibada** [comment]
I think it might also be reasonable as I found that in another R package, the author of the library that this package used is also added: https://github.com/hrbrmstr/htmltidy/blob/master/DESCRIPTION

**Comment by jhamman** [comment]
Yes, I think just citing the VIC-5 model and paper would suffice here:

- Hamman, J. J., Nijssen, B., Bohn, T. J., Gergel, D. R., and Mao, Y.: The Variable Infiltration Capacity model version 5 (VIC-5): infrastructure improvements for new applications and reproducibility, Geosci. Model Dev., 11, 3481-3496, https://doi.org/10.5194/gmd-11-3481-2018, 2018.
- Joe Hamman, Bart Nijssen, Ted Bohn, Wietse Franssen, Yixin Mao, and Diana Gergel. (2017, February 1). UW-Hydro/VIC: VIC 5.0.1 (Version VIC.5.0.1). Zenodo. http://doi.org/10.5281/zenodo.267178
