### ISSUE TITLE
Lake parameter validation should not be performed for cells in which lake_idx == -1

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#813]
- Version: VIC 5.1.0
- Model settings: image driver; `LAKES == TRUE`
- Description:
When `LAKES==TRUE`, `vic_init()` attempts to validate the lake parameters of all grid cells, even if `lake_idx == -1` (which ostensibly should turn off lakes for that cell). As a result, lake parameters that are set to `nodata` values are treated as if they are intended to be real parameter values. Similarly, `vic_force()` looks for a `channel_in` forcing variable, but it is conceivable that the user intends for lakes to be fed only by local runoff within the grid cell and has not prepared a `channel_in` input variable. `channel_in` is not a standard meteorological forcing, so forcing the user to create a `channel_in` variable that is potentially 0 everywhere seems a little much.
- Proposed solution:
Make validation of lake parameters conditional on `lake_idx >= 0` and make reading of `channel_in` conditional on `param_set[CHANNEL_IN].SUPPLIED==TRUE`.

**Comment by jhamman** [comment]
@tbohn - I'm glad to see the lake module getting some exercise (read thanks for the recent PRs cleaning things up). Do we have what would need to build a complete sample test case that uses the lakes module? This is probably going to be increasing important going forward.

**Comment by tbohn** [comment]
I'll need to check my various old project files.  The files I tested this on are miscellaneous grid cells from one of our projects at ASU, but these are not a simple, clean test case of a single lake, and certainly don't have accompanying observations. So, it depends on what you need - science tests or something more like a unit test that's at the level of the lake model as a whole.

**Comment by itzetoile** [comment]
Hi there, 
Glad to see the progress on the lake module. I have tested the lake module for Stehekin basin and it seems to work fine. However, I do not understand the functionality of channel_in in VIC5. Once a file is provided for it, it does not seem to do any further calculations with it. So basically only saving what was provided. Was this intended for further developement or did I missed something?  What should be the units for the numbers provided for channel_in, m3?

**Comment by tbohn** [comment]
`CHANNEL_IN` is supposed to be an input into the lake module. It is supposed to be added to the lake in `water_balance()`, called by `vic_run()`. The units should be mm/timestep; it gets converted to m3/timestep in `vic_run()`. Now that I think about it, mm/timestep is not a great choice for the units; one would think you'd have channel flow in units of m3 (either from observations or from a simulation). I suppose it is convenient if you've got total runoff from an upstream grid cell of approximately the same area. But it is counterintuitive...  Maybe we ought to change it.

**Comment by itzetoile** [comment]
Hi Ted, Thank you. That was very useful. I have now managed to run a test using channel_in. It would be, indeed, more intuitive to use m3, but the conversion is not too complicated. 
I am, however, still puzzled by this variable. As output, I saw it should be possible to save OUT_LAKE_CHAN_OUT and OUT_DISCHARGE, but I did not see any calculations for this in the code. If I would like to add this, how should I calculate them. Do you know?  Was there a reason for this not to be included?

**Comment by tbohn** [comment]
These were not included as output variables because in VIC, all of a grid
cell's runoff + baseflow is assumed to enter the channel network within the
grid cell. So the variables you would want to use would be simply the sum
of OUT_RUNOFF and OUT_BASEFLOW.

**Comment by itzetoile** [comment]
I see, that make sense. Thank you
