### ISSUE TITLE
Problems when installing the vic image driver

### ISSUE THREAD

**Issue by ted17001** [UW-Hydro/VIC#816]
Hi, everyone. I just start to learn vic recently.
When I install the vic image driver following the instructions, I met some problems. I've attached the screenshot.
"fatal: Not a git repository (or any parent up to point /home)"
And those warnings
If anyone knows how to fix it, please do me this favor. Thanks

![screenshot from 2018-09-04 11-39-24](https://user-images.githubusercontent.com/41239382/45337977-dc259480-b558-11e8-9081-b8b1d2c15b3b.png)
![screenshot from 2018-09-04 11-39-37](https://user-images.githubusercontent.com/41239382/45337978-dcbe2b00-b558-11e8-93b1-dfa5890ed8e4.png)

**Comment by jhamman** [comment]
It looks like your compilation succeeded. The git and compile warnings are unfortunate but can be safely ignored.
