### ISSUE TITLE
Esoil is 0 for pure bare soil tiles

### ISSUE THREAD

**Issue by tbohn** [UW-Hydro/VIC#821]
- VIC version: 5.1.0
- Compiler and OS: n/a
- Problem: when VIC encounters pure bare soil tiles, and uses a default value of `fcanopy` of `1` (e.g., no `fcanopy` values were specified in the params file), no soil evap (`esoil`) occurs, and no ET occurs. The reason for this appears to be that, in `func_surf_energy_bal()`, the logic surrounding the call to `arno_evap()` only calls `arno_evap()` if `fcanopy < 1`. The intent of the logic was for tiles with sparse vegetation (`fcanopy < 1`) to have `esoil` take place over the fractional area `(1-fcanopy)`. However, this logic neglected the default case in which `fcanopy == 1` for all tiles.
- Proposed solution:
-- Remove the extra line in `vic_init()` that sets `fcanopy = 1` in all tiles; this line is unnecessary as it immediately follows an `if-else` block that sets `fcanopy` to either `1` for tile index < `Nveg - 1` or `MIN_FCANOPY` for index == `Nveg - 1`.
-- Additionally handle the case in which `LAI == 0`; in this case, we should set `fcanopy` to `0` as well so that `esoil` can take place.
-- Add logic around all places where we divide a variable by `fcanopy`, to not do the division if `fcanopy == 0`.
-- Add a missing multiplication by `fcanopy` for `Evap` and `Wdew` inside `func_canopy_energy_bal()`.

**Comment by dgergel** [comment]
@tbohn Actually in `func_surf_energy_bal()`, `arno_evap` is still getting called when `fcanopy == 1`, but the `esoil` that is added to the `layer_data_struct` is multiplied by `1 - veg_var->fcanopy`, so when `fcanopy == 1` for bare soil (incorrectly), then `esoil` is multiplied by 0, resulting in what is calculated by `arno_evap` being 0.

**Comment by tbohn** [comment]
Addressed in PR #823
