### ISSUE TITLE
VIC RUNTIME ERROR

### ISSUE THREAD

**Issue by manas171993** [UW-Hydro/VIC#825]
Hi everyone, I am new to VIC model. I am getting the following error during VIC run. Kindly give some suggestion. Thanks in advance.

- Version : VIC.4.1.2.a)
- Operating system: Ubuntu 12.04
COMPILE-TIME OPTIONS (set in user_def.h)
----------------------------------------

Output to Screen:
OUTPUT_FORCE_STATS	FALSE
VERBOSE			TRUE

Input Files:
NO_REWIND		FALSE

Output Files:
OUTPUT_FORCE		FALSE

Simulation Parameters:
CLOSE_ENERGY		FALSE
LOW_RES_MOIST		FALSE
QUICK_FS		FALSE
SPATIAL_FROST		FALSE
SPATIAL_SNOW		FALSE
EXCESS_ICE		FALSE

Maximum Array Sizes:
MAX_BANDS		10
MAX_FRONTS		 3
MAX_LAKE_NODES		20
MAX_LAYERS		 3
MAX_NODES		50
MAX_VEG			12

Snow Constants:
NEW_SNOW_ALB		0.850000
SNOW_ALB_ACCUM_A	0.940000
SNOW_ALB_ACCUM_B	0.580000
SNOW_ALB_THAW_A		0.820000
SNOW_ALB_THAW_B		0.460000
TraceSnow		0.030000

Other Constants:
LAI_WATER_FACTOR	0.200000
LWAVE_COR		1.000000
MAXIT_FE		25

RUN-TIME OPTIONS (set in global parameter file)
-----------------------------------------------
Simulation Dimensions:
NLAYER			3
EQUAL_AREA		FALSE
RESOLUTION		-99999.000000
TIME_STEP		24
SNOW_STEP		1
STARTYEAR		2000
STARTMONTH		1
STARTDAY		1
STARTHOUR		0
ENDYEAR			2005
ENDMONTH		12
ENDDAY			31

Simulation Parameters:
AERO_RESIST_CANSNOW		AR_406_FULL
BLOWING			FALSE
COMPUTE_TREELINE		FALSE
CONTINUEONERROR		TRUE
CORRPREC		FALSE
DIST_PRCP		FALSE
EXP_TRANS		FALSE
FROZEN_SOIL		FALSE
FULL_ENERGY		FALSE
GRND_FLUX_TYPE		GF_410
LW_TYPE		LW_TVA
LW_CLOUD		LW_CLOUD_DEARDORFF
IMPLICIT		FALSE
NOFLUX			FALSE
MTCLIM_SWE_CORR		TRUE
PLAPSE		TRUE
QUICK_FLUX		TRUE
QUICK_SOLVE		FALSE
SNOW_ALBEDO		USACE
SNOW_DENSITY		DENS_BRAS
SW_PREC_THRESH		0.000000
TFALLBACK		TRUE
VP_INTERP		TRUE
VP_ITER		VP_ITER_ALWAYS
PREC_EXPT		0.600000
WIND_H			10.000000
MEASURE_H		2.000000
NODES			3
MIN_RAIN_TEMP		-0.500000
MAX_SNOW_TEMP		0.500000
MIN_WIND_SPEED		0.100000

Input Forcing Data:
Forcing File 1:		/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/forcing-India/data_*
FORCEYEAR		1951
FORCEMONTH		1
FORCEDAY		1
FORCEHOUR		0
N_TYPES			3
FORCE_DT		24
FORCE_ENDIAN		LITTLE
FORCE_FORMAT		ASCII
GRID_DECIMAL		2
ALMA_INPUT		FALSE

Input Soil Data:
Soil file		/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/Soil_parameter
ARC_SOIL		FALSE
BASEFLOW		ARNO
JULY_TAVG_SUPPLIED		FALSE
ORGANIC_FRACT		FALSE

Input Veg Data:
Veg library file	/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/Veg_Lib
Veg param file		/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/VEGPARAM_India_3_depth
ROOT_ZONES		3
VEGPARAM_LAI		FALSE
LAI_SRC		LAI_FROM_VEGLIB

Input Elevation Data:
SNOW_BAND		1	(no input file needed for SNOW_BAND=1)

Input Lake Data:
LAKES		FALSE
LAKE_PROFILE		FALSE

Input State File:
INIT_STATE		FALSE

Output State File:
SAVE_STATE		FALSE

Output Data:
Result dir:		/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/RESULTS
OUT_STEP		24
ALMA_OUTPUT		FALSE
BINARY_OUTPUT		FALSE
COMPRESS		FALSE
MOISTFRACT		FALSE
PRT_HEADER		FALSE
PRT_SNOW_BAND		FALSE
SKIPYEAR		0

Time Step = 24 hour(s)
Simulation start date = 01/01/2000
Simulation end date = 31/12/2005

Full Energy...................(0)
Use Distributed Precipitation.(0)
Ground heat flux will be estimated using Liang, Wood and Lettenmaier (1999).
Use Frozen Soil Model.........(0)
.... Using the explicit solution for the soil heat equation.
.... Thermal nodes are linearly distributed with depth (except top two nodes).
Run Snow Model Using a Time Step of 1 hours
Compress Output Files.........(0)
Correct Precipitation.........(0)

Using 1 Snow Bands
Using 3 Root Zones
Model output is in standard ASCII format.

 "./manas1/input_vic_India/global_param.INDIA" has been
  opened for reading.... skipping header

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/Soil_parameter" has been
  opened for reading.... skipping header

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/Veg_Lib" has been
  opened for reading.... skipping header

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/VEGPARAM_India_3_depth" has been
  opened for reading.

cell: 1,  lat: 37.0000, long: 74.2500

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/forcing-India/data_37.00_74.25" has been
  opened for reading.

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/RESULTS/fluxes_37.00_74.25" has been
  truncated or created for writing.

 "/home/hemantkumar/Work/hydroModel/VIC/manas1/input_vic_India/RESULTS/snow_37.00_74.25" has been
  truncated or created for writing.
Initializing Forcing Data
Model run-time error...
Input meteorological forcing files must contain either WIND (wind speed) or both WIND_N (north component of wind speed) and WIND_E (east component of wind speed); check input files

...now exiting to system...

**Comment by jhamman** [comment]
It looks like your forcings are missing wind (as the error message suggests).
