### ISSUE TITLE
readme.md file little error

### ISSUE THREAD

**Issue by kiritokun07** [UW-Hydro/VIC#851]
#### Bug Reports
There is a little error in the readme.md.
******************************************************
[![Documentation Status](https://readthedocs.org/projects/vic/badge/?version=latest]](http://vic.readthedocs.org/en/latest/)
******************************************************
you added a redundant "]" in readme.md.
It's not appropriate.
following is the correct way
[![Documentation Status](https://readthedocs.org/projects/vic/badge/?version=latest](http://vic.readthedocs.org/en/latest/)

**Comment by jhamman** [comment]
Thanks @kiritokun07. I'm not sure how this snuck in. Mind submitting a quick PR to fix this?

**Comment by jhamman** [comment]
closed via #852
