### ISSUE TITLE
VIC5.0.0/classic fatal error: execinfo.h: No such file or directory

### ISSUE THREAD

**Issue by lokendrarathore** [UW-Hydro/VIC#856]
#### Bug Reports

- Version of VIC that you are using-  VIC.5.0.0
- Name and version of the C compiler you are using- GCC
- Operating system- windows
- A description of relevant model settings
- A summary of the bug or error message you are getting-  fatal error: execinfo.h: No such file or directory

I am compiling VIC5.0.0 in windows 7 using cygwin, it gives error message when I give make commmand.
The error is- fatal error: execinfo.h: No such file or directory
What could be the issue and how to solve it.
Thanks

**Comment by jhamman** [comment]
It would seem you are missing the `execinfo.h` header in your environment. You should note VIC is not supported on Windows at this time and we don't test builds with cygwin so I wouldn't be surprised if you run into problems here. You may consider trying Docker instead, which we have found to work on Windows machines in the past.
