### ISSUE TITLE
Configuring time step in VIC Routing

### ISSUE THREAD

**Issue by ZubaeyrOdin** [UW-Hydro/VIC#857]
Hello,

I have been using VIC Hydrology Model for last couple of years to generate the runoff and soil-moisture data, at 6 hours time-step.

Recently, I have tried to integrate it with VIC Routing Model to calculate the inflow at given stations/points, but was unsuccessful as they was no scope of configuring it to 6 hour time-step. It seems to be available at 'day' time-step.

I am not sure if this is possible with VIC routing. Can you guys please help me out?

**Comment by jhamman** [comment]
Take a look at RVIC: https://github.com/UW-Hydro/RVIC
