### ISSUE TITLE
VIC5.0.1: fatal error: execinfo.h: No such file or directory  in cygwin, when make command is given

### ISSUE THREAD

**Issue by lokendrarathore** [UW-Hydro/VIC#859]
#### Bug Reports
fatal error: execinfo.h: No such file or directory after giving make command for classic driver in cygwin

- Version of VIC that you are using (e.g. VIC.5.0.1)
- Name and version of the C compiler you are using Cygwin
- Operating system  windows 7
- A description of relevant model settings
- A summary of the bug or error message you are getting

#### Feature Requests

- Description of feature
- Description of the problem the feature addresses
- Will the proposed feature be backward compatible?
- Will the proposed feature change the science results of VIC?

**Comment by liao007** [comment]
same question

**Comment by jhamman** [comment]
VIC is not tested or supported on Windows or Cygwin. I suggest reading FAQ#1 here: https://vic.readthedocs.io/en/master/FAQ/FAQ/ for more information.
