### ISSUE TITLE
VIC 5.1.0 download

### ISSUE THREAD

**Issue by rlilhare** [UW-Hydro/VIC#900]
Hello,
I just want to download the latest version of VIC 5?

I am just confused between VIC 5.0.1 and VIC 5.1?

Which is the latest version? 
When I download both and check the version using ./vic_classic.exe -v, it shows 5.0.1 for both of them.

**Comment by jhamman** [comment]
5.1 was never released. There is a release candidate though: https://github.com/UW-Hydro/VIC/releases
