### ISSUE TITLE
New - Compile failure -- Resolved

### ISSUE THREAD

**Issue by ZhengWang1003** [UW-Hydro/VIC#930]
#### Bug Reports

- VIC-WUR
- Cygwin or Linux
- When I execute make, I get the following error. Can anyone help me?
![image](https://user-images.githubusercontent.com/113409208/222960680-f52eb177-ec8b-4564-a8d8-a97fac2e3f59.png)

when i change the mpicc to gcc in file of Makefile, another error occurred (as follows)
#
ifndef MPICC
MPICC = gcc
endif
#
![image](https://user-images.githubusercontent.com/113409208/222960821-e82e540d-d6ea-470d-8390-a60814736637.png)

**Comment by XiaoXiaoLeisure** [comment]
Hi, I'm new to VIC5.0 and linux. Could you give me some specific advice on how to compile the VIC 5.0 Image Driver?
Like, what lines in the Makefile should I edit?
